package sistema;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



//import Clases.FileDownloader;
import Clases.GestorTime;
import Clases.clsConnection;
import Clases.clsFunciones;
import Clases.clsGlobales;
import Clases.clsOperacionesUsuarios;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *     
 * @author Richard
 */
public class Constancia_Suficiencia_Brigadista extends javax.swing.JInternalFrame {

    clsConnection oConn = new clsConnection();
    clsFunciones oFunc = new clsFunciones();
    clsOperacionesUsuarios oPe = new clsOperacionesUsuarios();

    public Constancia_Suficiencia_Brigadista() {
        initComponents();
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        FechaHoy = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cargoo_de = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bnnoapto = new javax.swing.JRadioButton();
        bnapto = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnImp = new javax.swing.JButton();
        txtimp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNorden = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("CONSENTIMIENTO BRIGADISTA");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Se hace constar que el Señor(a):"));
        jPanel1.setDoubleBuffered(false);

        jLabel2.setText("Yo");

        jLabel5.setText("identificado con DNI:");

        jLabel7.setText("<html>, ha sido evaluado de la normativa vigente, estando (APTO /NO APTO) para efectuar trabajos o actividades como brigadistas. <html>");

        FechaHoy.setDateFormatString(" EEEEE dd MMMMM yyyy");

        jLabel8.setText(", con el cargo de ");

        jLabel38.setText("Hora :");

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel9.setText(" de :");

        jLabel6.setText("años de edad,");

        jLabel10.setText(" de la empresa");

        jLabel1.setText(" La vigencia de esta constancia es del");

        jLabel3.setText("<html>A su vez se hace constar que se le ha informado al colaborador sobre los resultados Médicos Ocupacionales que se le practicaron en la fecha.<html>");

        buttonGroup1.add(bnnoapto);
        bnnoapto.setText("NO APTO");

        buttonGroup1.add(bnapto);
        bnapto.setText("APTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cargoo_de, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(bnapto)
                        .addGap(52, 52, 52)
                        .addComponent(bnnoapto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargoo_de, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(FechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnapto)
                    .addComponent(bnnoapto))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrar.png"))); // NOI18N
        btnGuardar.setText("Guardar/Actualizar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora.png"))); // NOI18N
        btnImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpActionPerformed(evt);
            }
        });

        txtimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimpActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("N° Ficha :");

        txtNorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNordenActionPerformed(evt);
            }
        });
        txtNorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNordenKeyTyped(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtimp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImp)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNorden, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtimp)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static com.toedter.calendar.JDateChooser FechaNacimiento;

    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date HorNew = new Date();
            SimpleDateFormat fechaforma = new SimpleDateFormat("hh:mm:ss a");
            String FfechaSystemA = fechaforma.format(HorNew);

            GestorTime.setFfechaSystem(FfechaSystemA);
            lblHora.setText(GestorTime.getFfechaSystem());
        }
    });


    private void txtNordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNordenActionPerformed
           
        FechaNacimiento = new com.toedter.calendar.JDateChooser();
       if(!txtNorden.getText().isEmpty()){
        if(!OrdenExiste()){  
       String Sql="select d.nombres_pa||' '||d.apellidos_pa AS nombre, d.cod_pa, "
               + "d.fecha_nacimiento_pa, n.razon_empresa,n.cargo_de"
               + " from datos_paciente AS d "
             + "INNER JOIN n_orden_ocupacional AS n ON (d.cod_pa=n.cod_pa) "
               + "WHERE n.n_orden ="+txtNorden.getText();
         oConn.FnBoolQueryExecute(Sql);
                try {
                    if (oConn.setResult.next()) {
                        txtNombre.setText(oConn.setResult.getString("nombre"));
                        txtDNI.setText(oConn.setResult.getString("cod_pa"));
                        FechaNacimiento.setDate(oConn.setResult.getDate("fecha_nacimiento_pa"));
                        txtEdad.setText(String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar())) );
                        txtEmpresa.setText(oConn.setResult.getString("razon_empresa"));      
                        cargoo_de.setText(oConn.setResult.getString("cargo_de"));      
                          
                        txtNorden.setEditable(false);
                        bnapto.setSelected(true);
                     //   FechaHoy.requestFocusInWindow();
                         Fecha();
                       }else{
                        oFunc.SubSistemaMensajeError("No se encuentra Algunos Registros necesarios(Alta en Ex-Ocupacionales)");
                    }
                oConn.setResult.close();
                oConn.sqlStmt.close();    
            } catch (SQLException ex) {
            oFunc.SubSistemaMensajeInformacion("Constancia:" + ex.getMessage().toString());}
       
        }
           } 
    }//GEN-LAST:event_txtNordenActionPerformed
public boolean OrdenExiste()
    {
        boolean bResultado=false;
        if(!txtNorden.getText().isEmpty()){
        String sQuery;

        sQuery  = "Select n_orden from consta_brigadista Where n_orden ="+txtNorden.getText();
        oConn.FnBoolQueryExecute(sQuery);
        try {
            if (oConn.setResult.next())
            {
                bResultado = true;
//             oFunc.SubSistemaMensajeError("Número de Orden Utilizado");
//             txtNorden.setText(null);
            }
            oConn.setResult.close();
            oConn.sqlStmt.close();
        } catch (SQLException ex) {
         
        }
        }       
        return bResultado;
        }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private boolean Grabar() throws SQLException {
    boolean bResult = false;

    // Formatear la fecha a YYYY-MM-DD
    String fechaFormateada = new java.text.SimpleDateFormat("yyyy-MM-dd")
        .format(FechaHoy.getDate());

    
    boolean esActivo = bnapto.isSelected();
    // Si prefieres que bnnoapto desactive:
    if (bnnoapto.isSelected()) {
        esActivo = false;
    }

    // Construir el INSERT con StringBuilder
    StringBuilder strSqlStmt = new StringBuilder();
    strSqlStmt.append("INSERT INTO consta_brigadista (n_orden, fecha, user_registro, es_activo) ")
              .append("VALUES (")
              .append(txtNorden.getText()).append(", ")                  // n_orden
              .append("'").append(fechaFormateada).append("', ")         // fecha
              .append("'").append(clsGlobales.sUser).append("',")  
            .append(esActivo)
              .append(")");// user_registro
         

    // Ejecutar la inserción
    if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt.toString())) {
        bResult = true;
        oFunc.SubSistemaMensajeInformacion("Constancia registrada correctamente");
    }

    // Cerrar el statement
    try {
        oConn.sqlStmt.close();
    } catch (SQLException ex) {
        Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName())
              .log(Level.SEVERE, null, ex);
    }

    return bResult;
}


    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         if(OrdenExiste()){  
            Actualizar();
         }else{
              if(!txtNorden.getText().isEmpty()){
            try {
              
                if(Grabar()){
                    imprimir();
                    limpiar();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName()).log(Level.SEVERE, null, ex);
            }     catch (IOException ex) {
                      Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName()).log(Level.SEVERE, null, ex);
                  }
           }
         }
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpActionPerformed
        
        if(!txtimp.getText().isEmpty()){
          
            try {
                print(Integer.valueOf(txtimp.getText()));
            } catch (IOException ex) {
                Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName()).log(Level.SEVERE, null, ex);
            }
 
        }
    }//GEN-LAST:event_btnImpActionPerformed

    private void txtNordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNordenKeyTyped
       oFunc.NoLetras(evt);
    }//GEN-LAST:event_txtNordenKeyTyped

    private void txtimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimpActionPerformed
    	
        if(!txtimp.getText().isEmpty()){
             
            try {
                print(Integer.valueOf(txtimp.getText()));
            } catch (IOException ex) {
                Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName()).log(Level.SEVERE, null, ex);
            }
 
        }
    }//GEN-LAST:event_txtimpActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        FechaNacimiento = new com.toedter.calendar.JDateChooser();

        String sCodigo = txtNorden.getText();
    String sql = ""
        + "SELECT "
        + "  d.cod_pa, "
        + "  d.nombres_pa || ' ' || d.apellidos_pa AS nombre, "
        + "  d.fecha_nacimiento_pa, "
        + "  n.razon_empresa, "
        + "  n.cargo_de, "
        + "  c.fecha AS fecha_constancia,c.es_activo "
        + "FROM datos_paciente d "
        + "INNER JOIN n_orden_ocupacional n ON d.cod_pa = n.cod_pa "
        + "INNER JOIN consta_brigadista c ON c.n_orden = n.n_orden "
        + "WHERE n.n_orden = " + sCodigo;

    // Ejecutar la consulta
    if (!oConn.FnBoolQueryExecute(sql)) {
        oFunc.SubSistemaMensajeError("Error al ejecutar consulta de Constancia Brigadista");
        return;
    }

    try {
        if (oConn.setResult.next()) {
            // Paciente
            txtNombre.setText(oConn.setResult.getString("nombre"));
            txtDNI.setText(oConn.setResult.getString("cod_pa"));
            FechaNacimiento.setDate(oConn.setResult.getDate("fecha_nacimiento_pa"));

            // Empresa / Cargo
            txtEmpresa.setText(oConn.setResult.getString("razon_empresa"));
            cargoo_de.setText(oConn.setResult.getString("cargo_de"));

            // Fecha de la constancia
            FechaHoy.setDate(oConn.setResult.getDate("fecha_constancia"));

            // Edad calculada
            int edad = oFunc.calcularEdad(FechaNacimiento.getCalendar());
            txtEdad.setText(String.valueOf(edad));
            if(oConn.setResult.getBoolean("es_activo"))
                bnapto.setSelected(true);
            else
                bnnoapto.setSelected(true);
                
            
            // Nota: user_registro no se carga aquí, pues siempre usamos clsGlobales.sUser al grabar/actualizar
        } else {
            oFunc.SubSistemaMensajeError("No se encontraron registros para la orden " + sCodigo);
        }
    } catch (SQLException ex) {
        oFunc.SubSistemaMensajeError("Error al leer resultados: " + ex.getMessage());
    } finally {
        try {
            if (oConn.setResult != null) oConn.setResult.close();
            if (oConn.sqlStmt   != null) oConn.sqlStmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName())
                  .log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
     //   cerrarVentana();
    }//GEN-LAST:event_formInternalFrameClosing
    private void print(Integer cod) throws IOException{
                         
    Map<String, Object> parameters = new HashMap<>();
    parameters.put("Norden", cod);

    // Recuperar DNI del paciente desde tu tabla consta_brigadista
   
    // Consumir API para obtener el sello en Base64

                
                try 
                { String direccionReporte = "";
                   direccionReporte = System.getProperty("user.dir") + File.separator + "reportes" + File.separator + "Constancia de suficiencia_medicapara_Brigadista_boro.jasper";
                    
                        
                    JasperReport myReport = (JasperReport) JRLoader.loadObjectFromFile(direccionReporte);
                        JasperPrint myPrint = JasperFillManager.fillReport(myReport, parameters, clsConnection.oConnection);
                        JasperViewer viewer = new JasperViewer(myPrint, false);
                        viewer.setTitle("CONSTANCIA BRIGADISTA");
                        // viewer.setAlwaysOnTop(true);
                        viewer.setVisible(true);
                   
                 } catch (JRException ex) {
                    Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
 
 }
     
   private void Actualizar() {
    String sCodigo = txtNorden.getText();
    // Formatear la fecha a YYYY-MM-DD
    String fechaFormateada = new java.text.SimpleDateFormat("yyyy-MM-dd")
        .format(FechaHoy.getDate());
    
     boolean esActivo = bnapto.isSelected();
    // Si prefieres que bnnoapto desmarque es_activo aunque bnapto esté marcado:
    if (bnnoapto.isSelected()) {
        esActivo = false;
    }

    // Construir el UPDATE para consta_brigadista
    StringBuilder strSqlStmt = new StringBuilder();
    strSqlStmt.append("UPDATE consta_brigadista ")
              .append("SET fecha = '").append(fechaFormateada).append("', ")
              .append("user_registro = '").append(clsGlobales.sUser).append("', ")
              .append("  es_activo   = ").append(esActivo)  // true o false sin comillas
              .append(" WHERE n_orden = ").append(sCodigo);
              System.out.println(strSqlStmt.toString());
    // Ejecutar la actualización
    if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt.toString())) {
        oFunc.SubSistemaMensajeInformacion("Registro de constancia actualizado con éxito");
        // Si quieres imprimir o limpiar, descomenta estas líneas:
         limpiar();
    } else {
        oFunc.SubSistemaMensajeError("No se pudo actualizar el registro");
    }

    // Cerrar el statement
    try {
        oConn.sqlStmt.close();
    } catch (SQLException ex) {
        Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName())
              .log(Level.SEVERE, null, ex);
    }
}

    private boolean imprimir() throws IOException{
    boolean im = false;
int seleccion = JOptionPane.showOptionDialog(
    this, // Componente padre
    "¿Desea Imprimir?", //Mensaje
    "Seleccione una opción", // Título
    JOptionPane.YES_NO_CANCEL_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,    // null para icono por defecto.
    new Object[] { "Si", "No"},    // null para YES, NO y CANCEL
    "Si");
    if (seleccion != -1)
    {
   if((seleccion + 1)==1)
   {
       
     printer(Integer.valueOf(txtNorden.getText().toString()));
      
        im = true;
   }
   else
   {
      // PRESIONO NO
     }
    }
    return im;

}
  private void printer(Integer cod) throws IOException {
    if (cod == null || cod <= 0) {
        JOptionPane.showMessageDialog(this,
            "Código inválido para generar el reporte.",
            "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Preparar parámetros
    Map<String, Object> parameters = new HashMap<>();
    parameters.put("Norden", cod);

    // Recuperar DNI del paciente desde tu tabla consta_brigadista
    
 
    // Consumir API para obtener el sello en Base64
    
    // Elegir plantilla según presencia de sello digitalizado
    String masterJasper;
    masterJasper = System.getProperty("user.dir")
                     + File.separator + "reportes"
                     + File.separator + "Constancia de suficiencia_medicapara_Brigadista_boro.jasper";
    
    File reportFile = new File(masterJasper);
    if (!reportFile.exists()) {
        JOptionPane.showMessageDialog(this,
            "No se encontró el reporte en: " + masterJasper,
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Cargar y ejecutar Jasper
    try {
        JasperReport jasper  = (JasperReport) JRLoader.loadObject(reportFile);
        JasperPrint  print   = JasperFillManager.fillReport(
                                  jasper, parameters, clsConnection.oConnection);
        JasperPrintManager.printReport(print, true);
    } catch (JRException ex) {
        JOptionPane.showMessageDialog(this,
            "Error al generar el reporte: " + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

 
  
private void limpiar(){
txtNombre.setText(null);
txtDNI.setText(null);
txtEmpresa.setText(null);
txtEdad.setText(null);
FechaHoy.setDate(null);
txtNorden.setText(null);
txtNorden.setEditable(true);
txtNorden.requestFocus();
cargoo_de.setText(null);
bnapto.setSelected(true);
}
void Fecha(){
Date fechaDate = new Date();
//SimpleDateFormat formateador = new SimpleDateFormat("'HUAMACHUCO - ' EEEEE dd MMMMM yyyy");
FechaHoy.setDate(fechaDate);
}

public void cerrarVentana(){
        // JOptionPane.showMessageDialog(null, "probando para cerrar el stament");
        System.out.println("cerro esta ventana");
        try {
            oConn.sqlStmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Constancia_Suficiencia_Brigadista.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    this.dispose();
      //  System.exit(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaHoy;
    private javax.swing.JRadioButton bnapto;
    private javax.swing.JRadioButton bnnoapto;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImp;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cargoo_de;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNorden;
    private javax.swing.JTextField txtimp;
    // End of variables declaration//GEN-END:variables
}
