/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistema;

//import Clases.FileDownloader;
import Clases.GestorTime;
import Clases.clsConnection;
import Clases.clsFunciones;
import Clases.clsGlobales;
import Clases.clsOperacionesUsuarios;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *     
 * @author Richard
 */
public class Constancia_LecturaYEntrega_ResultadosEMO_boro extends javax.swing.JInternalFrame {

    clsConnection oConn = new clsConnection();
    clsFunciones oFunc = new clsFunciones();
    clsOperacionesUsuarios oPe = new clsOperacionesUsuarios();

    public Constancia_LecturaYEntrega_ResultadosEMO_boro() {
        initComponents();
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FechaHoy1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtApellidosNombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPuestoTrabajo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FechaHoy2 = new com.toedter.calendar.JDateChooser();
        lblHora = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnImp = new javax.swing.JButton();
        txtimp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNorden = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        FechaHoy = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        txtTipoEMO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        FechaHoy1.setDateFormatString(" EEEEE dd MMMMM yyyy");

        setClosable(true);
        setResizable(true);
        setTitle("Constancia  lectura y Entrega de resultados");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Se hace constar que el Señor(a):"));
        jPanel1.setDoubleBuffered(false);

        jLabel2.setText("Nombres:");

        jLabel5.setText("identificado con DNI:");

        jLabel7.setText("Mediante el presente dejo constancia que el Médico Ocupacional representante de la empresa");

        jLabel8.setText(", con el cargo de ");

        txtEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmpresaActionPerformed(evt);
            }
        });

        jLabel9.setText(" de :");

        jLabel6.setText("años de edad,");

        jLabel1.setText("<html>me ha entregado, informado y explicado de manera presencial o por medios  <br>digitales los resultados del Examen Médico Ocupacional que se me ha realizado.  <br>Así mismo me comprometo a cumplir con las indicaciones y recomendaciones recibidas por parte del médico ocupacional.<html>");

        jLabel3.setText("Doy conformidad de lo indicado mediante mi firma y/o huella digital:");

        FechaHoy2.setDateFormatString(" EEEEE dd MMMMM yyyy");

        lblHora.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPuestoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidosNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(FechaHoy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidosNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPuestoTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FechaHoy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrar.png"))); // NOI18N
        btnGuardar.setText("Guardar/Actualizar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnImp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora.png"))); // NOI18N
        btnImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImpActionPerformed(evt);
            }
        });

        txtimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtimpActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("N° Ficha :");

        txtNorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNordenActionPerformed(evt);
            }
        });
        txtNorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNordenKeyTyped(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        FechaHoy.setDateFormatString(" EEEEE dd MMMMM yyyy");

        jLabel4.setText("Fecha EMO:");

        txtTipoEMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoEMOActionPerformed(evt);
            }
        });

        jLabel10.setText("Tipo EMO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtimp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImp)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNorden, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTipoEMO, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtNorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar)
                        .addComponent(jLabel4))
                    .addComponent(FechaHoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTipoEMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtimp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static com.toedter.calendar.JDateChooser FechaNacimiento;

    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date HorNew = new Date();
            SimpleDateFormat fechaforma = new SimpleDateFormat("hh:mm:ss a");
            String FfechaSystemA = fechaforma.format(HorNew);

            GestorTime.setFfechaSystem(FfechaSystemA);
            lblHora.setText(GestorTime.getFfechaSystem());
        }
    });


    private void txtNordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNordenActionPerformed
        FechaNacimiento = new com.toedter.calendar.JDateChooser();

        String orden = txtNorden.getText().trim();
    if (orden.isEmpty()) {
        oFunc.SubSistemaMensajeError("Por favor ingrese un número de orden.");
        return;
    }
    if (OrdenExiste()) {
        oFunc.SubSistemaMensajeError("La orden ya existe en el sistema.");
        return;
    }
    String sql = ""
      + "SELECT "
      + "  d.nombres_pa || ' ' || d.apellidos_pa AS nombre, "
      + "  d.cod_pa, "
      + "  d.fecha_nacimiento_pa, "
      + "  n.razon_empresa, "
      + "  n.cargo_de, "
      + "  n.fecha_apertura_po, "    
      + "  n.nom_examen "
      + "FROM datos_paciente AS d "
      + "INNER JOIN n_orden_ocupacional AS n "
      + "  ON d.cod_pa = n.cod_pa "
      + "WHERE n.n_orden = " + orden;
    System.out.println(sql);

    if (!oConn.FnBoolQueryExecute(sql)) {
        oFunc.SubSistemaMensajeError("Error al ejecutar la consulta de paciente/orden.");
        return;
    }

    try {
        if (oConn.setResult.next()) {
            txtApellidosNombres.setText(oConn.setResult.getString("nombre"));
            txtDNI.setText( oConn.setResult.getString("cod_pa") );

            Date fnac = oConn.setResult.getDate("fecha_nacimiento_pa");
            FechaNacimiento.setDate(fnac);
            txtEdad.setText(
              String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar()))
            );

            txtEmpresa.setText(      oConn.setResult.getString("razon_empresa") );
            txtPuestoTrabajo.setText(oConn.setResult.getString("cargo_de")     );
            txtTipoEMO.setText(    oConn.setResult.getString("nom_examen")    );

            Date fechaEMO = oConn.setResult.getDate("fecha_apertura_po");
            FechaHoy.setDate(fechaEMO);

            txtNorden.setEditable(false);
            Fecha();  
        } else {
            oFunc.SubSistemaMensajeError(
              "No se encontró paciente u orden. Verifique el número ingresado."
            );
        }
    } catch (SQLException ex) {
        oFunc.SubSistemaMensajeInformacion("Error al leer datos: " + ex.getMessage());
    } finally {
        // 5) Cerrar siempre los recursos
        try {
            if (oConn.setResult != null) oConn.setResult.close();
            if (oConn.sqlStmt   != null) oConn.sqlStmt.close();
        } catch (SQLException ignore) {}
    }
    }//GEN-LAST:event_txtNordenActionPerformed
   public boolean OrdenExiste() {
    boolean bResultado = false;
    String orden = txtNorden.getText().trim();
    if (!orden.isEmpty()) {
      
        String sQuery = "SELECT n_orden FROM registro_conformidad_emo WHERE n_orden = " + orden;
        oConn.FnBoolQueryExecute(sQuery);
        try {
            if (oConn.setResult.next()) {
                bResultado = true;
            }
        } catch (SQLException ex) {
            oFunc.SubSistemaMensajeInformacion("Error al comprobar existencia de orden: " + ex.getMessage());
        } finally {
           
            try {
                if (oConn.setResult != null) oConn.setResult.close();
                if (oConn.sqlStmt   != null) oConn.sqlStmt.close();
            } catch (SQLException ignore) {}
        }
    }
    return bResultado;
}

    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

   private boolean GrabarConformidad() throws SQLException {
    boolean bResult = false;

    // 1) Formatear fechas a YYYY-MM-DD
    SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
    String fechaEMO    = fmt.format(FechaHoy.getDate());
    String fechaEntreg = fmt.format(FechaHoy2.getDate());

    // 2) Construir el INSERT
    StringBuilder sql = new StringBuilder();
    sql.append("INSERT INTO registro_conformidad_emo ")
       .append("(n_orden, fecha_emo, tipo_emo, apellidos_nombres, dni, puesto_trabajo, fecha_entrega, user_registro) VALUES (")
       // n_orden
       .append(txtNorden.getText().trim()).append(", ")
       // fecha_emo
       .append("'").append(fechaEMO).append("', ")
       // tipo_emo
       .append("'").append(txtTipoEMO.getText().trim()).append("', ")
       // apellidos_nombres
       .append("'").append(txtApellidosNombres.getText().trim()).append("', ")
       // dni
       .append("'").append(txtDNI.getText().trim()).append("', ")
       // puesto_trabajo
       .append("'").append(txtPuestoTrabajo.getText().trim()).append("', ")
       // fecha_entrega
       .append("'").append(fechaEntreg).append("', ")
       // user_registro
       .append("'").append(clsGlobales.sUser).append("')")
       ;

    System.out.println(sql.toString());

    // 3) Ejecutar la inserción
    if (oConn.FnBoolQueryExecuteUpdate(sql.toString())) {
        bResult = true;
        oFunc.SubSistemaMensajeInformacion("Registro de conformidad grabado correctamente");
    }

    // 4) Cerrar el statement
    try {
        oConn.sqlStmt.close();
    } catch (SQLException ex) {
        Logger.getLogger(this.getClass().getName())
              .log(Level.SEVERE, null, ex);
    }

    return bResult;
}



    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
         if(OrdenExiste()){  
           ActualizarConformidad();
         }else{
              if(!txtNorden.getText().isEmpty()){
            try {
              
                if(GrabarConformidad()){
                    imprimir();
                    limpiar();
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Constancia_LecturaYEntrega_ResultadosEMO_boro.class.getName()).log(Level.SEVERE, null, ex);
            }     catch (IOException ex) {
                      Logger.getLogger(Constancia_LecturaYEntrega_ResultadosEMO_boro.class.getName()).log(Level.SEVERE, null, ex);
                  }
           }
         }
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImpActionPerformed
        
        if(!txtimp.getText().isEmpty()){
          
            try {
                print(Integer.valueOf(txtimp.getText()));
            } catch (IOException ex) {
                Logger.getLogger(Constancia_LecturaYEntrega_ResultadosEMO_boro.class.getName()).log(Level.SEVERE, null, ex);
            }
 
        }
    }//GEN-LAST:event_btnImpActionPerformed

    private void txtNordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNordenKeyTyped
       oFunc.NoLetras(evt);
    }//GEN-LAST:event_txtNordenKeyTyped

    private void txtimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtimpActionPerformed
    	
        if(!txtimp.getText().isEmpty()){
             
            try {
                print(Integer.valueOf(txtimp.getText()));
            } catch (IOException ex) {
                Logger.getLogger(Constancia_LecturaYEntrega_ResultadosEMO_boro.class.getName()).log(Level.SEVERE, null, ex);
            }
 
        }
    }//GEN-LAST:event_txtimpActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
              FechaNacimiento = new com.toedter.calendar.JDateChooser();

        String sCodigo = txtNorden.getText().trim();
    if (sCodigo.isEmpty()) {
        oFunc.SubSistemaMensajeError("Por favor ingrese un número de orden.");
        return;
    }

    String sql = ""
      + "SELECT "
      + "  d.cod_pa, "
      + "  d.nombres_pa || ' ' || d.apellidos_pa AS nombre, "
      + "  d.fecha_nacimiento_pa, "
      + "  n.razon_empresa, "
      + "  n.cargo_de, "
      + "  c.fecha_emo, "
      + "  c.tipo_emo, "
      + "  c.fecha_entrega "
      + "FROM datos_paciente d "
      + "INNER JOIN n_orden_ocupacional n ON d.cod_pa = n.cod_pa "
      + "INNER JOIN registro_conformidad_emo c ON c.n_orden = n.n_orden "
      + "WHERE n.n_orden = " + sCodigo;

    // Ejecutar la consulta
    if (!oConn.FnBoolQueryExecute(sql)) {
        oFunc.SubSistemaMensajeError("Error al ejecutar consulta de Conformidad EMO");
        return;
    }

    try {
        if (oConn.setResult.next()) {
            // Paciente
            txtApellidosNombres.setText(oConn.setResult.getString("nombre"));
            txtDNI.setText(          oConn.setResult.getString("cod_pa"));
            FechaNacimiento.setDate( oConn.setResult.getDate("fecha_nacimiento_pa"));

            // Empresa / Cargo
            txtEmpresa.setText(      oConn.setResult.getString("razon_empresa"));
            txtPuestoTrabajo.setText(oConn.setResult.getString("cargo_de"));

            // Tipo de EMO
            txtTipoEMO.setText(      oConn.setResult.getString("tipo_emo"));

            // Fecha EMO y Fecha de entrega
            FechaHoy .setDate(oConn.setResult.getDate("fecha_emo"));
            FechaHoy2.setDate(oConn.setResult.getDate("fecha_entrega"));

            // Edad calculada
            int edad = oFunc.calcularEdad(FechaNacimiento.getCalendar());
            txtEdad.setText(String.valueOf(edad));
        } else {
            oFunc.SubSistemaMensajeError("No se encontraron registros para la orden " + sCodigo);
        }
    } catch (SQLException ex) {
        oFunc.SubSistemaMensajeError("Error al leer resultados: " + ex.getMessage());
    } finally {
        try {
            if (oConn.setResult != null) oConn.setResult.close();
            if (oConn.sqlStmt   != null) oConn.sqlStmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(this.getClass().getName())
                  .log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
       // cerrarVentana();
    }//GEN-LAST:event_formInternalFrameClosing

    private void txtEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresaActionPerformed

    private void txtTipoEMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoEMOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoEMOActionPerformed
    private void print(Integer cod) throws IOException{
    Map<String, Object> parameters = new HashMap<>();
    parameters.put("Norden", cod);

   
    
              

    // Elegir plantilla según presencia de sello digitalizado

                try 
                {    String direccionReporte;
                            direccionReporte = System.getProperty("user.dir")
                            + File.separator + "reportes"
                             + File.separator + "Constancia_lecturayentregade_resultados_boro.jasper";
                       
                        JasperReport myReport = (JasperReport) JRLoader.loadObjectFromFile(direccionReporte);
                        JasperPrint myPrint = JasperFillManager.fillReport(myReport, parameters, clsConnection.oConnection);
                        JasperViewer viewer = new JasperViewer(myPrint, false);
                        viewer.setTitle("CONSTANCIA BRIGADISTA");
                        // viewer.setAlwaysOnTop(true);
                        viewer.setVisible(true);
                   
                 } catch (JRException ex) {
                    Logger.getLogger(Constancia_LecturaYEntrega_ResultadosEMO_boro.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
 
 }
     
  private void ActualizarConformidad() {
    String sCodigo = txtNorden.getText().trim();
    if (sCodigo.isEmpty()) {
        oFunc.SubSistemaMensajeError("Por favor ingrese un número de orden.");
        return;
    }

    // Formatear la fecha EMO a YYYY-MM-DD
    String fechaFormateada = new java.text.SimpleDateFormat("yyyy-MM-dd")
        .format(FechaHoy.getDate());

    // Construir el UPDATE para tu tabla registro_conformidad_emo
    StringBuilder strSqlStmt = new StringBuilder();
    strSqlStmt.append("UPDATE registro_conformidad_emo ")
              .append("SET ")
              .append("  fecha_emo      = '").append(fechaFormateada).append("', ")
              .append("  user_registro  = '").append(clsGlobales.sUser).append("' ")
              .append("WHERE n_orden = ").append(sCodigo);

    System.out.println(strSqlStmt.toString());

    // Ejecutar la actualización
    if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt.toString())) {
        oFunc.SubSistemaMensajeInformacion("Registro de conformidad actualizado con éxito");
        // Si necesitas refrescar la pantalla o limpiar campos, hazlo aquí:
        // limpiarFormulario();
    } else {
        oFunc.SubSistemaMensajeError("No se pudo actualizar el registro de conformidad");
    }

    // Cerrar el statement
    try {
        if (oConn.sqlStmt != null) oConn.sqlStmt.close();
    } catch (SQLException ex) {
        Logger.getLogger(this.getClass().getName())
              .log(Level.SEVERE, null, ex);
    }
}


    private boolean imprimir() throws IOException{
    boolean im = false;
int seleccion = JOptionPane.showOptionDialog(
    this, // Componente padre
    "¿Desea Imprimir?", //Mensaje
    "Seleccione una opción", // Título
    JOptionPane.YES_NO_CANCEL_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,    // null para icono por defecto.
    new Object[] { "Si", "No"},    // null para YES, NO y CANCEL
    "Si");
    if (seleccion != -1)
    {
   if((seleccion + 1)==1)
   {
       
     printer(Integer.valueOf(txtNorden.getText().toString()));
      
        im = true;
   }
   else
   {
      // PRESIONO NO
     }
    }
    return im;

}
  private void printer(Integer cod) throws IOException {
    if (cod == null || cod <= 0) {
        JOptionPane.showMessageDialog(this,
            "Código inválido para generar el reporte.",
            "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Preparar parámetros
    Map<String, Object> parameters = new HashMap<>();
    parameters.put("Norden", cod);



    // Elegir plantilla según presencia de sello digitalizado
    String masterJasper;
        masterJasper = System.getProperty("user.dir")
                     + File.separator + "reportes"
                     + File.separator + "Constancia_lecturayentregade_resultados_boro.jasper";
    

    File reportFile = new File(masterJasper);
    if (!reportFile.exists()) {
        JOptionPane.showMessageDialog(this,
            "No se encontró el reporte en: " + masterJasper,
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Cargar y ejecutar Jasper
    try {
        JasperReport jasper  = (JasperReport) JRLoader.loadObject(reportFile);
        JasperPrint  print   = JasperFillManager.fillReport(
                                  jasper, parameters, clsConnection.oConnection);
        JasperPrintManager.printReport(print, true);
    } catch (JRException ex) {
        JOptionPane.showMessageDialog(this,
            "Error al generar el reporte: " + ex.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
}

 
  
private void limpiar() {
    
    txtApellidosNombres.setText(null);
    txtDNI.setText(null);
    FechaNacimiento.setDate(null);    
    txtEdad.setText(null);
    txtEmpresa.setText(null);
    txtPuestoTrabajo.setText(null);
    txtTipoEMO.setText(null);       
    txtTipoEMO.setText(null);        
    FechaHoy .setDate(null);         
    FechaHoy2.setDate(null);        
    txtNorden.setText(null);
    txtNorden.setEditable(true);
    txtNorden.requestFocus();
 
}


void Fecha(){
Date fechaDate = new Date();
//SimpleDateFormat formateador = new SimpleDateFormat("'HUAMACHUCO - ' EEEEE dd MMMMM yyyy");
FechaHoy.setDate(fechaDate);
FechaHoy2.setDate(fechaDate);
}

public void cerrarVentana(){
        // JOptionPane.showMessageDialog(null, "probando para cerrar el stament");
        System.out.println("cerro esta ventana");
        try {
            oConn.sqlStmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(Constancia_LecturaYEntrega_ResultadosEMO_boro.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    this.dispose();
      //  System.exit(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaHoy;
    private com.toedter.calendar.JDateChooser FechaHoy1;
    private com.toedter.calendar.JDateChooser FechaHoy2;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImp;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHora;
    private javax.swing.JTextField txtApellidosNombres;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNorden;
    private javax.swing.JTextField txtPuestoTrabajo;
    private javax.swing.JTextField txtTipoEMO;
    private javax.swing.JTextField txtimp;
    // End of variables declaration//GEN-END:variables
}
