/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import Caja.RegistrarCliente;
//import Clases.FileDownloader;
import Clases.clsConnection;
import Clases.clsFunciones;
import Clases.clsGlobales;
import Clases.clsOperacionesUsuarios;
import com.toedter.calendar.JDateChooser;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import sun.misc.BASE64Decoder;

/**
 *
 * @author admin
 */
public class Consentimientos extends javax.swing.JInternalFrame {

    clsConnection oConn = new clsConnection();
    clsFunciones  oFunc = new clsFunciones();
    clsOperacionesUsuarios oPe = new clsOperacionesUsuarios();
    String[]aintelectual = new String[]{};
    DefaultTableModel model;
   public Consentimientos() {
       
      initComponents();
      
      cargarMedicos();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   
   
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        txtImprimir6 = new javax.swing.JTextField();
        btnImprimir12 = new javax.swing.JButton();
        btnLimpiar7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel88 = new javax.swing.JLabel();
        crit_donde_6 = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        crit_cuando_5 = new javax.swing.JTextField();
        crit_cual_4 = new javax.swing.JTextField();
        ant_boro_6 = new javax.swing.JRadioButton();
        ant_boro_5 = new javax.swing.JRadioButton();
        crit_fecha_3 = new com.toedter.calendar.JDateChooser();
        ant_boro_4 = new javax.swing.JRadioButton();
        crit_cual_2 = new javax.swing.JTextField();
        ant_boro_3 = new javax.swing.JRadioButton();
        crit_cual_1 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        txtnombre6 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        txtedad6 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        txtdni6 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtNorden6 = new javax.swing.JTextField();
        btnEditar7 = new javax.swing.JButton();
        jLabel124 = new javax.swing.JLabel();
        FechaEx6 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        txtempresa1 = new javax.swing.JTextField();
        trabajador = new javax.swing.JRadioButton();
        postulante = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        cboMedicoBoro = new javax.swing.JComboBox();
        chkMasticaHCoca = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotas = new javax.swing.JTextArea();

        jMenu1.setText("jMenu1");

        setClosable(true);
        setTitle("LABORATORIO");

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IMPRIMIR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 11), new java.awt.Color(0, 0, 102))); // NOI18N

        txtImprimir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImprimir6ActionPerformed(evt);
            }
        });

        btnImprimir12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora.png"))); // NOI18N
        btnImprimir12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtImprimir6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtImprimir6)
            .addComponent(btnImprimir12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 512, -1, -1));

        btnLimpiar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar7.setMnemonic('l');
        btnLimpiar7.setText("Limpiar");
        btnLimpiar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar7ActionPerformed(evt);
            }
        });
        jPanel16.add(btnLimpiar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 523, 127, -1));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrar.png"))); // NOI18N
        jButton8.setText("Guardar/Actualizar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 523, -1, -1));

        jLabel88.setText("Especifique dónde: ");
        jPanel16.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));
        jPanel16.add(crit_donde_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 121, -1));

        jLabel87.setText("Especifique cuándo: ");
        jPanel16.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        crit_cuando_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crit_cuando_5ActionPerformed(evt);
            }
        });
        jPanel16.add(crit_cuando_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 121, -1));
        jPanel16.add(crit_cual_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 183, -1));

        ant_boro_6.setText("<HTML>¿En las últimas 48 horas, se realizó algún tratamiento quirúrgico o dental?                  Especifique cuál: <HTML>");
        ant_boro_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant_boro_6ActionPerformed(evt);
            }
        });
        jPanel16.add(ant_boro_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 509, 27));

        ant_boro_5.setText("¿Consume regularmente mate de coca?            Especifique la fecha:");
        ant_boro_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant_boro_5ActionPerformed(evt);
            }
        });
        jPanel16.add(ant_boro_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        crit_fecha_3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                crit_fecha_3PropertyChange(evt);
            }
        });
        jPanel16.add(crit_fecha_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 124, -1));

        ant_boro_4.setText("¿Consume regularmente algún medicamento?            ¿Cuál? ");
        ant_boro_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant_boro_4ActionPerformed(evt);
            }
        });
        jPanel16.add(ant_boro_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel16.add(crit_cual_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 197, -1));

        ant_boro_3.setText("¿Sufre  alguna enfermedad?                                               ¿Cuál? ");
        ant_boro_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ant_boro_3ActionPerformed(evt);
            }
        });
        jPanel16.add(ant_boro_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 358, 29));
        jPanel16.add(crit_cual_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 197, -1));

        jLabel78.setText("Además, declaro que la información que brindaré a continuación es verdadera: ");
        jPanel16.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 440, -1));

        jLabel74.setText("<html>autorizo al  POLICLINICO HORIZONTE MEDIC, para que se me realice el examen toxicológico de drogas en orina y/o saliva, según los protocolos establecidos y que los resultados se entreguen directamente a la empresa.<html>");
        jPanel16.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 138, 722, 47));

        jLabel71.setText("Yo");
        jPanel16.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 81, -1, -1));
        jPanel16.add(txtnombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 78, 299, -1));

        jLabel72.setText("de");
        jPanel16.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 81, -1, -1));
        jPanel16.add(txtedad6, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 78, 33, -1));

        jLabel73.setText("años de edad, con documento de identidad N° ");
        jPanel16.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 81, -1, -1));

        txtdni6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdni6ActionPerformed(evt);
            }
        });
        jPanel16.add(txtdni6, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 78, 77, -1));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel70.setText("CONSENTIMIENTO PARA REALIZAR LA PRUEBA DE DOSAJE DE MARIHUANA Y COCAÍNA");
        jPanel16.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 44, -1, -1));

        jLabel69.setText("Nro Orden :");
        jPanel16.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, 67, -1));

        txtNorden6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNorden6ActionPerformed(evt);
            }
        });
        jPanel16.add(txtNorden6, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 13, 99, -1));

        btnEditar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion.png"))); // NOI18N
        btnEditar7.setText("Editar");
        btnEditar7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar7ActionPerformed(evt);
            }
        });
        jPanel16.add(btnEditar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 13, -1, -1));

        jLabel124.setText("Fecha :");
        jPanel16.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 16, 45, -1));

        FechaEx6.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FechaEx6PropertyChange(evt);
            }
        });
        jPanel16.add(FechaEx6, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 13, 124, -1));

        jLabel14.setText("trabajador (  ");
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 109, -1, -1));

        txtempresa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempresa1ActionPerformed(evt);
            }
        });
        jPanel16.add(txtempresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 106, 391, -1));

        trabajador.setText(" ) o postulante (");
        trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadorActionPerformed(evt);
            }
        });
        jPanel16.add(trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 107, -1, -1));

        postulante.setText(" ), de la empresa  ");
        postulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postulanteActionPerformed(evt);
            }
        });
        jPanel16.add(postulante, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 107, -1, -1));

        jLabel23.setText("MEDICO:");
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, -1));

        cboMedicoBoro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar un doctor" }));
        cboMedicoBoro.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboMedicoBoroPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cboMedicoBoro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMedicoBoroActionPerformed(evt);
            }
        });
        cboMedicoBoro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboMedicoBoroKeyPressed(evt);
            }
        });
        jPanel16.add(cboMedicoBoro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 290, -1));

        chkMasticaHCoca.setText("¿Chaccha o mastica hoja de coca?");
        jPanel16.add(chkMasticaHCoca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel24.setText("Notas:");
        jPanel16.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txtNotas.setColumns(20);
        txtNotas.setRows(5);
        jScrollPane1.setViewportView(txtNotas);

        jPanel16.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 290, 90));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("BORO", jPanel15);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
     private void cargarMedicos(){
      String sQuery;        
        // Prepara el Query
        sQuery ="SELECT TRIM(UPPER(APELLIDO_USER))||' '||TRIM(UPPER(NOMBRE_USER)) as medico FROM USUARIOS ORDER BY MEDICO";
        
        if (oConn.FnBoolQueryExecute(sQuery))
        {
            try 
            {
                // Verifica resultados
                 while (oConn.setResult.next())
                 {                     
                     // Obtiene los datos de la Consulta
                    
                     cboMedicoBoro.addItem(oConn.setResult.getString ("medico"));
                 }
                 
                 // Cierra Resultados
              
            } 
            catch (SQLException ex) 
            {
                //JOptionPane.showMessageDialorootPane,ex);
                oFunc.SubSistemaMensajeInformacion(ex.toString());
                Logger.getLogger(Consentimientos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
                cboMedicoBoro.setSelectedItem("GARCIA CABRERA ARTEMIO ALEJANDRO");

        try {
            oConn.sqlStmt.close();
            oConn.setResult.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Consentimientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        // selecciona
        //cboSede.setSelectedIndex(1);
                
                cboMedicoBoro.setEnabled(false);

}
     
     private String buscarUserConDatosMedico(String medico){
      String sQuery="";        
        // Prepara el Query
        sQuery ="SELECT usuario_user  as medico FROM USUARIOS where TRIM(UPPER(APELLIDO_USER))||' '||TRIM(UPPER(NOMBRE_USER)) = '"+medico+"'";
        
        if (oConn.FnBoolQueryExecute(sQuery))
        {
            try 
            {
                // Verifica resultados
                 while (oConn.setResult.next())
                 {                     
                     // Obtiene los datos de la Consulta
                     sQuery=oConn.setResult.getString ("medico");

                 }
                 
                 // Cierra Resultados
              
            } 
            catch (SQLException ex) 
            {
                //JOptionPane.showMessageDialorootPane,ex);
                oFunc.SubSistemaMensajeInformacion(ex.toString());
                Logger.getLogger(Consentimientos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            oConn.sqlStmt.close();
            oConn.setResult.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Consentimientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        // selecciona
        //cboSede.setSelectedIndex(1);
        // selecciona
        //cboSede.setSelectedIndex(1);

        return sQuery;
}
       
    private com.toedter.calendar.JDateChooser FechaNacimiento;
    private void txtNorden6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNorden6ActionPerformed
        if(!txtNorden6.getText().isEmpty()){
            if(!oPe.nOrden(txtNorden6, "consent_Boro"))  {
                FechaNacimiento = new com.toedter.calendar.JDateChooser();
                String Sql="select d.nombres_pa||' '||d.apellidos_pa AS nombre , n.razon_empresa , d.cod_pa, d.fecha_nacimiento_pa , "
                + "n.cargo_de , EXTRACT(YEAR FROM age(current_date,d.fecha_nacimiento_pa)) AS  edad from datos_paciente AS d "
                + "INNER JOIN n_orden_ocupacional AS n ON (d.cod_pa=n.cod_pa) WHERE n.n_orden ='"+txtNorden6.getText()+"'";
                oConn.FnBoolQueryExecute(Sql);
            try {
                if (oConn.setResult.next()) {
                    txtnombre6.setText(oConn.setResult.getString("nombre"));                  
                    txtedad6.setText(oConn.setResult.getString("edad"));
                    txtdni6.setText(oConn.setResult.getString("cod_pa"));                                
                   oPe.fecha(FechaEx6);
                    txtempresa1.setText(oConn.setResult.getString("razon_empresa"));
                }else{
                    oFunc.SubSistemaMensajeError("No se encuentra Registro: \n 1- Intente de nuevo \n 2- Si el error sigue Registre Usuario o \n    Aperture EX-Preocupacional nuevamente");
                }
                oConn.setResult.close();
            } catch (SQLException ex) {
                oFunc.SubSistemaMensajeInformacion("CONSENTIMIENTO BORO:" + ex.getMessage());
            }
        }
            else
                oFunc.SubSistemaMensajeInformacion("Ya existe este registro ");
      }
    }//GEN-LAST:event_txtNorden6ActionPerformed

    private void btnEditar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar7ActionPerformed
          if(!txtNorden6.getText().isEmpty()){
            FechaNacimiento = new com.toedter.calendar.JDateChooser();
            String Sql="select d.nombres_pa||' '||d.apellidos_pa AS nombre, d.cod_pa, n.razon_empresa, d.fecha_nacimiento_pa,"
                + "cboro.*"
                +"FROM datos_paciente AS d  \n" 
                +"INNER JOIN n_orden_ocupacional AS n ON (d.cod_pa=n.cod_pa) \n" 
                +"INNER JOIN consent_Boro as cboro ON (n.n_orden=cboro.n_orden) " 
                +"WHERE n.n_orden ='"+txtNorden6.getText()+"'";
            System.out.println(Sql);
            oConn.FnBoolQueryExecute(Sql);
            try {
                if (oConn.setResult.next()) {
                        txtnombre6.setText(oConn.setResult.getString("nombre"));
                        txtdni6.setText(oConn.setResult.getString("cod_pa"));                                   
                        txtempresa1.setText(oConn.setResult.getString("razon_empresa"));
                        FechaNacimiento.setDate(oConn.setResult.getDate("fecha_nacimiento_pa"));
                        txtedad6.setText(String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar())));
                        trabajador.setSelected(oConn.setResult.getBoolean("trabajador"));
                        postulante.setSelected(oConn.setResult.getBoolean("postulante"));
                       // ant_boro_1.setSelected(oConn.setResult.getBoolean("ant_boro_1"));
                       // ant_boro_2.setSelected(oConn.setResult.getBoolean("ant_boro_2"));
                        ant_boro_3.setSelected(oConn.setResult.getBoolean("ant_boro_3"));
                        ant_boro_4.setSelected(oConn.setResult.getBoolean("ant_boro_4"));
                        ant_boro_5.setSelected(oConn.setResult.getBoolean("ant_boro_5"));
                        ant_boro_6.setSelected(oConn.setResult.getBoolean("ant_boro_6"));
                        crit_cual_1.setText(oConn.setResult.getString("crit_cual_1"));
                        crit_cual_2.setText(oConn.setResult.getString("crit_cual_2"));
                        crit_fecha_3.setDate(oConn.setResult.getDate("crit_fecha_3"));
                        crit_cual_4.setText(oConn.setResult.getString("crit_cual_4"));
                        crit_cuando_5.setText(oConn.setResult.getString("crit_cuando_5"));
                        crit_donde_6.setText(oConn.setResult.getString("crit_donde_6"));
                        FechaEx6.setDate(oConn.setResult.getDate("fechaEx"));
                        chkMasticaHCoca.setSelected(oConn.setResult.getBoolean("masticah_coca"));
                        txtNotas.setText(oConn.setResult.getString("notas"));
                                               
                }else{
                    oFunc.SubSistemaMensajeError("No se encuentra Registro: \n 1- Intente de nuevo \n 2- Si el error sigue Registre Usuario o \n    Aperture EX-Preocupacional");
                }
                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                oFunc.SubSistemaMensajeInformacion("Error:" + ex.getMessage());
            }

        }
    }//GEN-LAST:event_btnEditar7ActionPerformed

    private void FechaEx6PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FechaEx6PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaEx6PropertyChange

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         if(oPe.nOrden(txtNorden6, "consent_Boro"))  {
           Actualizar6();
       }else{
         Guardar6();
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnLimpiar7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar7ActionPerformed
       limpiar6();
    }//GEN-LAST:event_btnLimpiar7ActionPerformed

    private void txtImprimir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImprimir6ActionPerformed
        
    }//GEN-LAST:event_txtImprimir6ActionPerformed

    private void btnImprimir12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir12ActionPerformed
       imp6(txtImprimir6.getText().trim());
    }//GEN-LAST:event_btnImprimir12ActionPerformed

    private void ant_boro_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant_boro_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ant_boro_3ActionPerformed

    private void ant_boro_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant_boro_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ant_boro_4ActionPerformed

    private void ant_boro_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant_boro_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ant_boro_5ActionPerformed

    private void ant_boro_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ant_boro_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ant_boro_6ActionPerformed

    private void crit_fecha_3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_crit_fecha_3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_crit_fecha_3PropertyChange

    private void txtdni6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdni6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdni6ActionPerformed

    private void crit_cuando_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crit_cuando_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crit_cuando_5ActionPerformed

    private void txtempresa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempresa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempresa1ActionPerformed

    private void postulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postulanteActionPerformed
         if (postulante.isSelected())
            {
            trabajador.setSelected(false);   
            }
    }//GEN-LAST:event_postulanteActionPerformed

    private void trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadorActionPerformed
       if (trabajador.isSelected())
            {
            postulante.setSelected(false);   
            }
    }//GEN-LAST:event_trabajadorActionPerformed

    private void cboMedicoBoroPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboMedicoBoroPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicoBoroPopupMenuWillBecomeInvisible

    private void cboMedicoBoroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMedicoBoroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicoBoroActionPerformed

    private void cboMedicoBoroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboMedicoBoroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMedicoBoroKeyPressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaEx6;
    private javax.swing.JRadioButton ant_boro_3;
    private javax.swing.JRadioButton ant_boro_4;
    private javax.swing.JRadioButton ant_boro_5;
    private javax.swing.JRadioButton ant_boro_6;
    private javax.swing.JButton btnEditar7;
    private javax.swing.JButton btnImprimir12;
    private javax.swing.JButton btnLimpiar7;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cboMedicoBoro;
    private javax.swing.JRadioButton chkMasticaHCoca;
    private javax.swing.JTextField crit_cual_1;
    private javax.swing.JTextField crit_cual_2;
    private javax.swing.JTextField crit_cual_4;
    private javax.swing.JTextField crit_cuando_5;
    private javax.swing.JTextField crit_donde_6;
    private com.toedter.calendar.JDateChooser crit_fecha_3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton postulante;
    private javax.swing.JRadioButton trabajador;
    private javax.swing.JTextField txtImprimir6;
    private javax.swing.JTextField txtNorden6;
    private javax.swing.JTextArea txtNotas;
    private javax.swing.JTextField txtdni6;
    private javax.swing.JTextField txtedad6;
    private javax.swing.JTextField txtempresa1;
    private javax.swing.JTextField txtnombre6;
    // End of variables declaration//GEN-END:variables
    
   
   

 
   //VALIDAR PANEL 10D

  //ACTUALIZAR DATA PANEL 5D  

  //GUARDAR DATA DE PANEL 5D

// VALIDAR PANEL 5D

   

  //ACTUALIZAR DATA PANEL 3D  

  //GUARDAR DATA DE PANEL 3D

// VALIDAR PANEL 3D

  //ACTUALIZAR DATA PANEL 2D  


  //GUARDAR DATA DE PANEL 2D




 //ACTUALIZAR DATA MUESTRA SANGRE


  //GUARDAR DATA MUESTRA SANGRE

// VALIDAR MUESTRA SANGRE


  //GUARDAR DATA MUESTRA SANGRE


 //ACTUALIZAR DATA CONSENTIMIENTO BORO
public void Actualizar6() {
    String sCodigo = txtNorden6.getText(); // Número de orden
    if (!txtNorden6.getText().isEmpty()) {
        if (validar6()) { // Verifica que los campos sean válidos
            StringBuilder strSqlStmt = new StringBuilder();
            strSqlStmt.append("UPDATE consent_Boro SET ");
            
            if (!trabajador.isSelected() && !postulante.isSelected()) {
                oFunc.SubSistemaMensajeError("Debe seleccionar si es postulante o trabajador.");
                return;
            }
            // Campos booleanos siempre se actualizan
            strSqlStmt.append("trabajador=").append(trabajador.isSelected()).append(", ");
            strSqlStmt.append("postulante=").append(postulante.isSelected()).append(", ");
           // strSqlStmt.append("ant_boro_1=").append(ant_boro_1.isSelected()).append(", ");
           // strSqlStmt.append("ant_boro_2=").append(ant_boro_2.isSelected()).append(", ");
            strSqlStmt.append("ant_boro_3=").append(ant_boro_3.isSelected()).append(", ");
            strSqlStmt.append("ant_boro_4=").append(ant_boro_4.isSelected()).append(", ");
            strSqlStmt.append("ant_boro_5=").append(ant_boro_5.isSelected()).append(", ");
            strSqlStmt.append("ant_boro_6=").append(ant_boro_6.isSelected()).append(", ");
            strSqlStmt.append("user_medico_ocup='").append(buscarUserConDatosMedico(cboMedicoBoro.getSelectedItem().toString())).append("', ");
            

            // Campos condicionales según ant_boro_X
            // Validación y actualización de campos dependientes
            if (ant_boro_3.isSelected()) {
                if (crit_cual_1.getText().trim().isEmpty()) {
                    oFunc.SubSistemaMensajeError("Debe escribir ¿Cual Enfermedad?");
                    return;
                }
                strSqlStmt.append("crit_cual_1='").append(crit_cual_1.getText().trim()).append("', ");
            } else {
                strSqlStmt.append("crit_cual_1=NULL, ");
            }

            if (ant_boro_4.isSelected()) {
                if (crit_cual_2.getText().trim().isEmpty()) {
                    oFunc.SubSistemaMensajeError("Debe escribir ¿Cual Medicamento? ");
                    return;
                }
                strSqlStmt.append("crit_cual_2='").append(crit_cual_2.getText().trim()).append("', ");
            } else {
                strSqlStmt.append("crit_cual_2=NULL, ");
            }

            if (ant_boro_5.isSelected()) {
                if (crit_fecha_3.getDate() == null) {
                    oFunc.SubSistemaMensajeError("Debe ingresar una fecha");
                    return;
                }
                strSqlStmt.append("crit_fecha_3='")
                          .append(new java.sql.Date(crit_fecha_3.getDate().getTime()))
                          .append("', ");
            } else {
                strSqlStmt.append("crit_fecha_3=NULL, ");
            }

            if (ant_boro_6.isSelected()) {
                if (crit_cual_4.getText().trim().isEmpty()) {
                    oFunc.SubSistemaMensajeError("Debe escribir ¿Cual?");
                    return;
                }
                if (crit_cuando_5.getText().trim().isEmpty()) {
                    oFunc.SubSistemaMensajeError("Debe escribir ¿Cuando?");
                    return;
                }
                if (crit_donde_6.getText().trim().isEmpty()) {
                    oFunc.SubSistemaMensajeError("Debe escribir ¿Donde?");
                    return;
                }
                strSqlStmt.append("crit_cual_4='").append(crit_cual_4.getText().trim()).append("', ");
                strSqlStmt.append("crit_cuando_5='").append(crit_cuando_5.getText().trim()).append("', ");
                strSqlStmt.append("crit_donde_6='").append(crit_donde_6.getText().trim()).append("', ");
            } else {
                strSqlStmt.append("crit_cual_4=NULL, ");
                strSqlStmt.append("crit_cuando_5=NULL, ");
                strSqlStmt.append("crit_donde_6=NULL, ");
            }
            strSqlStmt.append("masticah_coca=").append(chkMasticaHCoca.isSelected()).append(", ");
            strSqlStmt.append("notas='").append(txtNotas.getText().trim().replace("'", "''")).append("', ");
            


           if (strSqlStmt.toString().endsWith(", ")) {
               strSqlStmt.setLength(strSqlStmt.length() - 2);
            }
           String fechaFormateada = null;
            if (FechaEx6.getDate() != null) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                fechaFormateada = dateFormat.format(FechaEx6.getDate());
            }
            if (fechaFormateada != null) {
                strSqlStmt.append(", fechaEx='").append(fechaFormateada).append("' ");
            }

            strSqlStmt.append(" WHERE n_orden=").append(sCodigo);

            String finalQuery = strSqlStmt.toString();
            System.out.println("El comando es: " + finalQuery);

            try {
                if (oConn.FnBoolQueryExecuteUpdate(finalQuery)) {
                    oFunc.SubSistemaMensajeInformacion("Se ha actualizado con éxito");
                    imp6(txtNorden6.getText().trim()); //
                    limpiar6(); // Limpia los campos
                    txtNorden6.setEnabled(true);
                    txtNorden6.requestFocus();
                } else {
                    oFunc.SubSistemaMensajeError("No se pudo registrar la entrada");
                }
            } finally {
                try {
                    if (oConn.sqlStmt != null) {
                        oConn.sqlStmt.close();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(EvaluacionMusculoEsqueletica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            oFunc.SubSistemaMensajeError("Llene los campos correctamente");
            txtNorden6.requestFocus();
        }
    } else {
        oFunc.SubSistemaMensajeError("El campo de número de orden está vacío");
        txtNorden6.requestFocus();
    }
}
  //GUARDAR DATA CONSETIMIENTO BORO
public void Guardar6() {
    if (!txtNorden6.getText().isEmpty()) {
        if (!oPe.nOrden(txtNorden6, "consent_Boro")) { 
            if (validar6()) { 
                if (!trabajador.isSelected() && !postulante.isSelected()) {
                    oFunc.SubSistemaMensajeError("Debe seleccionar si es postulante o trabajador.");
                    return;
                }
                
                StringBuilder strSqlStmt = new StringBuilder();
                StringBuilder query = new StringBuilder();

                strSqlStmt.append("INSERT INTO consent_Boro (");
                query.append("VALUES (");

                // Añadimos el número de orden
                strSqlStmt.append("n_orden, ");
                query.append(txtNorden6.getText()).append(", ");

                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String fechaFormateada = dateFormat.format(FechaEx6.getDate());

               
                strSqlStmt.append("fechaEx, ");
                query.append("'").append(fechaFormateada).append("', "); 
                
                strSqlStmt.append("trabajador, ");
                query.append(trabajador.isSelected()).append(", ");
                
                strSqlStmt.append("postulante, ");
                query.append(postulante.isSelected()).append(", ");
                
         //       strSqlStmt.append("ant_boro_1, ");
           //     query.append(ant_boro_1.isSelected()).append(", ");

          //      strSqlStmt.append("ant_boro_2, ");
            //    query.append(ant_boro_2.isSelected()).append(", ");

               
                strSqlStmt.append("ant_boro_3, ");
                query.append(ant_boro_3.isSelected()).append(", ");

                strSqlStmt.append("crit_cual_1, ");
                if (ant_boro_3.isSelected()) {
                    if (crit_cual_1.getText().trim().isEmpty()) {
                        oFunc.SubSistemaMensajeError("Debe escribir la enfermedad");
                        return;
                    }
                    query.append("'").append(crit_cual_1.getText().trim()).append("', ");
                } else {
                    query.append("NULL, ");
                }
              
                strSqlStmt.append("ant_boro_4, ");
                query.append(ant_boro_4.isSelected()).append(", ");

                strSqlStmt.append("crit_cual_2, ");
                if (ant_boro_4.isSelected()) {
                    if (crit_cual_2.getText().trim().isEmpty()) {
                        oFunc.SubSistemaMensajeError("Debe completar ¿Cual? ");
                        return;
                    }
                    query.append("'").append(crit_cual_2.getText().trim()).append("', ");
                } else {
                    query.append("NULL, ");
                }
               
                
                strSqlStmt.append("ant_boro_5, ");
                query.append(ant_boro_5.isSelected()).append(", ");

                strSqlStmt.append("crit_fecha_3, ");
                if (ant_boro_5.isSelected()) {
                    if (crit_fecha_3.getDate() == null) {
                        oFunc.SubSistemaMensajeError("Debe ingresar la fecha");
                        return;
                    }
                    query.append("'").append(new java.sql.Date(crit_fecha_3.getDate().getTime())).append("', ");
                } else {
                    query.append("NULL, ");
                }
                
              
                strSqlStmt.append("ant_boro_6, ");
                query.append(ant_boro_6.isSelected()).append(", ");

                strSqlStmt.append("crit_cual_4, crit_cuando_5, crit_donde_6, ");
                if (ant_boro_6.isSelected()) {
                    if (crit_cual_4.getText().trim().isEmpty()) {
                        oFunc.SubSistemaMensajeError("Debe completar ¿Cual? ");
                        return;
                    }
                    if (crit_cuando_5.getText().trim().isEmpty()) {
                        oFunc.SubSistemaMensajeError("Debe completar ¿Cuando? ");
                        return;
                    }
                    if (crit_donde_6.getText().trim().isEmpty()) {
                        oFunc.SubSistemaMensajeError("Debe completar ¿Donde? ");
                        return;
                    }
                    query.append("'").append(crit_cual_4.getText().trim()).append("', ");
                    query.append("'").append(crit_cuando_5.getText().trim()).append("', ");
                    query.append("'").append(crit_donde_6.getText().trim()).append("', ");
                } else {
                    query.append("NULL, NULL, NULL, ");
                }
             
                // registro de usuario
               strSqlStmt.append("masticah_coca, ");query     .append(chkMasticaHCoca.isSelected()).append(", ");
               strSqlStmt.append("notas, ");query     .append("'").append(txtNotas.getText().trim().replace("'", "''")).append("', ");

                strSqlStmt.append("user_medico_ocup,");
                query.append("'").append(buscarUserConDatosMedico(cboMedicoBoro.getSelectedItem().toString())).append("', ");                
                
                strSqlStmt.append("user_registro");
                query.append("'").append(clsGlobales.sUser).append("'");
                // Cierra la consulta
                strSqlStmt.append(")");
                query.append(")");

                String finalQuery = strSqlStmt.toString() + " " + query.toString();
                System.out.println("El comando es: " + finalQuery);

                try {
                    if (oConn.FnBoolQueryExecuteUpdate(finalQuery)) {
                        oFunc.SubSistemaMensajeInformacion("Se ha guardado con éxito");
                        imp6(txtNorden6.getText().trim()); // Llamada a la función de impresión
                        limpiar6(); // Limpia los campos
                    } else {
                        oFunc.SubSistemaMensajeError("No se pudo guardar la entrada");
                    }
                } finally {
                    try {
                        if (oConn.sqlStmt != null) {
                            oConn.sqlStmt.close();
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(EvaluacionMusculoEsqueletica.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else {
                oFunc.SubSistemaMensajeError("Llene los campos correctamente");
            }
        } else {
            oFunc.SubSistemaMensajeError("El registro ya existe en la base de datos");
        }
    } else {
        oFunc.SubSistemaMensajeError("El campo de número de orden está vacío");
    }
}
// VALIDAR CONSETIMIENTO BORO
private boolean validar6(){
        boolean bResultado=true;
    if (((JTextField)FechaEx6.getDateEditor().getUiComponent()).getText().trim().length()< 2 ) 
        {oFunc.SubSistemaMensajeError("Ingrese Fecha");bResultado = false;}  
   return bResultado;
} 
   



//LIMPIAR PANEL10D 
private void limpiar6(){
        txtNorden6.setText(null);
        txtnombre6.setText(null);
        txtdni6.setText(null);
        txtedad6.setText(null);
        FechaEx6.setDate(null);
        txtempresa1.setText(null);
        trabajador.setSelected(false);
        postulante.setSelected(false);
     //   ant_boro_1.setSelected(false);
       // ant_boro_2.setSelected(false);
        ant_boro_3.setSelected(false);
        ant_boro_4.setSelected(false);
        ant_boro_5.setSelected(false);
        ant_boro_6.setSelected(false);
        chkMasticaHCoca.setSelected(false);
        crit_cual_1.setText(null);
        crit_cual_2.setText(null);
        crit_fecha_3.setDate(null);
        crit_cual_4.setText(null);
        crit_cuando_5.setText(null);
        crit_donde_6.setText(null);
        txtNotas.setText(null);
               
    }
    
    
     

// PARA IMPRIMER CONSETIMIENTO BORO
    private void imp6(String norden){
    if(!norden.isEmpty()){
            imprimir7(Integer.valueOf(norden));
        }else 
         oFunc.SubSistemaMensajeError("Numero de Orden no Existe");     
  }        





//IMPRIMIR MUESTRA DE BORO   
private void imprimir7(Integer num) {
    int seleccion = JOptionPane.showOptionDialog(
            this,
            "¿Desea Imprimir Hoja?",
            "Seleccione una opción",
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[]{"Si", "No"},
            "Si");

    if (seleccion == 0) { // Seleccionó "Sí"
        if (OrdenExiste7(num)) {
            try {
                printer7(num);
            } catch (IOException ex) {
                Logger.getLogger(Consentimientos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "El número de orden no existe.",
                    "Error", JOptionPane.WARNING_MESSAGE);
        }
    } else {
        System.out.println("Impresión cancelada por el usuario.");
    }
}
//MUESTRA EL JASPER
private void printer7(Integer cod) throws IOException {
    if (cod == null || cod <= 0) {
        JOptionPane.showMessageDialog(this, "Código inválido para generar el reporte.",
                "Error", JOptionPane.WARNING_MESSAGE);
        return;
    }
        Map<String, Object> parameters = new HashMap<>();
        parameters.put("Norden", cod);

                              
                String base64Huella="";
                String base64FirmaP="";
                String base64Sello=""; 
                String base64SelloDocAsig="";    

        

        
    String master =""; 
         
     master = System.getProperty("user.dir") + "/reportes/Consentimiento_Boro.jasper";
    
    File reportFile = new File(master);
    if (!reportFile.exists()) {
        JOptionPane.showMessageDialog(this, "El archivo del reporte no se encontró en: " + master,
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        JasperReport masterReport = (JasperReport) JRLoader.loadObject(reportFile);


        JasperPrint myPrint = JasperFillManager.fillReport(masterReport, parameters, clsConnection.oConnection);
        JasperPrintManager.printReport(myPrint, true);
       

// JasperViewer.viewReport(myPrint, false);
    } catch (JRException ex) {
        JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}
//VALIDA QUE EL NORDEN EXISTA EN LA TABLA
public boolean OrdenExiste7(Integer norden) {
    boolean bResultado = false;
    if (!String.valueOf(norden).isEmpty()) {
        String sQuery = "SELECT n_orden FROM consent_Boro WHERE n_orden = " + norden;
        try {
            oConn.FnBoolQueryExecute(sQuery);
            if (oConn.setResult != null && oConn.setResult.next()) {
                bResultado = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al consultar la base de datos: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (oConn.setResult != null) {
                    oConn.setResult.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    return bResultado;
}































}
