/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema;

import Clases.clsConnection;
import Clases.clsFunciones;
import Clases.clsGlobales;
import Clases.clsOperacionesUsuarios;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Administrador
 */
public class TestFatigaSomnolencia extends javax.swing.JInternalFrame {
    clsConnection oConn = new clsConnection();
    clsFunciones oFunc = new clsFunciones();
    clsOperacionesUsuarios oPe = new clsOperacionesUsuarios();
    DefaultTableModel model;

    public TestFatigaSomnolencia() {
        initComponents();
        txtMedico.setText( clsGlobales.sNomOperador +" - "+ clsGlobales.sCMPOperador );
    }
     private com.toedter.calendar.JDateChooser FechaNacimiento;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        bgS1 = new javax.swing.ButtonGroup();
        bgS2 = new javax.swing.ButtonGroup();
        bgS3 = new javax.swing.ButtonGroup();
        bgS4 = new javax.swing.ButtonGroup();
        bgS5 = new javax.swing.ButtonGroup();
        bgS6 = new javax.swing.ButtonGroup();
        bgS7 = new javax.swing.ButtonGroup();
        bgS8 = new javax.swing.ButtonGroup();
        bgS9 = new javax.swing.ButtonGroup();
        bgResultado = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FechaExamen = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsexo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtareatrabajo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtempresa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNorden = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSeparator1 = new javax.swing.JSeparator();
        btnEditar = new javax.swing.JButton();
        Tabla = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        rbS1Poca = new javax.swing.JRadioButton();
        rbS1Moderada = new javax.swing.JRadioButton();
        rbS1Alta = new javax.swing.JRadioButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        rbS1Nunca = new javax.swing.JRadioButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        rbS2Nunca = new javax.swing.JRadioButton();
        rbS2Poca = new javax.swing.JRadioButton();
        rbS2Moderada = new javax.swing.JRadioButton();
        rbS2Alta = new javax.swing.JRadioButton();
        rbS3Nunca = new javax.swing.JRadioButton();
        rbS3Poca = new javax.swing.JRadioButton();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        rbS3Moderada = new javax.swing.JRadioButton();
        rbS3Alta = new javax.swing.JRadioButton();
        rbS4Nunca = new javax.swing.JRadioButton();
        rbS4Poca = new javax.swing.JRadioButton();
        rbS4Moderada = new javax.swing.JRadioButton();
        rbS4Alta = new javax.swing.JRadioButton();
        rbS5Nunca = new javax.swing.JRadioButton();
        rbS5Poca = new javax.swing.JRadioButton();
        rbS5Moderada = new javax.swing.JRadioButton();
        rbS5Alta = new javax.swing.JRadioButton();
        rbS6Nunca = new javax.swing.JRadioButton();
        rbS6Poca = new javax.swing.JRadioButton();
        rbS6Moderada = new javax.swing.JRadioButton();
        rbS6Alta = new javax.swing.JRadioButton();
        rbS7Nunca = new javax.swing.JRadioButton();
        rbS7Poca = new javax.swing.JRadioButton();
        rbS7Moderada = new javax.swing.JRadioButton();
        rbS7Alta = new javax.swing.JRadioButton();
        rbS8Nunca = new javax.swing.JRadioButton();
        rbS8Poca = new javax.swing.JRadioButton();
        rbS8Moderada = new javax.swing.JRadioButton();
        rbS8Alta = new javax.swing.JRadioButton();
        rbS9Nunca = new javax.swing.JRadioButton();
        rbS9Poca = new javax.swing.JRadioButton();
        rbS9Moderada = new javax.swing.JRadioButton();
        rbS9Alta = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        rbNo = new javax.swing.JRadioButton();
        rbSi = new javax.swing.JRadioButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtPuntaje = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtMedico = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtImp = new javax.swing.JTextField();
        btnImprimir = new javax.swing.JButton();
        btLimpiar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 705, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TEST DE FATIGA Y SOMNOLENCIA");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filiación"));

        jLabel1.setText("Nombres :");

        txtNombres.setEditable(false);

        jLabel2.setText("Fecha :");

        jLabel3.setText("Edad :");

        txtEdad.setEditable(false);

        jLabel4.setText("Sexo :");

        txtsexo.setEditable(false);

        jLabel5.setText("DNI :");

        txtdni.setEditable(false);

        jLabel6.setText("Area de Trabajo :");

        txtareatrabajo.setEditable(false);

        jLabel7.setText("Empresa :");

        txtempresa.setEditable(false);

        jLabel8.setText("Nº Orden :");

        txtNorden.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNordenFocusGained(evt);
            }
        });
        txtNorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNordenActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/configuracion.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtareatrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNorden, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FechaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel2)
                    .addComponent(FechaExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtareatrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        jPanel16.setBackground(new java.awt.Color(153, 204, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "SITUACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel44.setText("1. Sentado leyendo ");

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 153));
        jLabel45.setText("Nunca ");

        rbS1Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS1.add(rbS1Poca);

        rbS1Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS1.add(rbS1Moderada);

        rbS1Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS1.add(rbS1Alta);

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 0, 153));
        jLabel56.setText("Poca ");

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 0, 153));
        jLabel57.setText("Moderada ");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 0, 153));
        jLabel58.setText("Alta");

        rbS1Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS1.add(rbS1Nunca);
        rbS1Nunca.setSelected(true);

        jLabel59.setText("2. Viendo televisión ");

        jLabel60.setText("<HTML>3. Sentado (por ejemplo en el teatro, en una reunión, en el cine, en una  conferencia, escuchando misa o en el culto) </HTML>");

        rbS2Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS2.add(rbS2Nunca);
        rbS2Nunca.setSelected(true);

        rbS2Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS2.add(rbS2Poca);

        rbS2Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS2.add(rbS2Moderada);

        rbS2Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS2.add(rbS2Alta);

        rbS3Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS3.add(rbS3Nunca);
        rbS3Nunca.setSelected(true);

        rbS3Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS3.add(rbS3Poca);

        jLabel67.setText("<HTML>4. Como pasajero en un automóvil, ómnibus, micro o combi durante una hora o  menos de recorrido </HTML>");

        jLabel68.setText("5. Recostado en la tarde si las corcunstancias lo permiten");

        jLabel69.setText("6. Sentado conversando con alguien");

        jLabel70.setText("7. Sentado luego del almuerzo y sin haber bebido alcohol ");

        jLabel71.setText("<HTML>8. Conduciendo el automóvil cuando se detiene algunos minutos por razones de tráfico </HTML>");

        jLabel83.setText("9. Parado y apoyándose o no en una pared o mueble");

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel41.setText("Probabilidad de cabecear");

        rbS3Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS3.add(rbS3Moderada);

        rbS3Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS3.add(rbS3Alta);
        rbS3Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS3AltaActionPerformed(evt);
            }
        });

        rbS4Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS4.add(rbS4Nunca);
        rbS4Nunca.setSelected(true);

        rbS4Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS4.add(rbS4Poca);

        rbS4Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS4.add(rbS4Moderada);

        rbS4Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS4.add(rbS4Alta);
        rbS4Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS4AltaActionPerformed(evt);
            }
        });

        rbS5Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS5.add(rbS5Nunca);
        rbS5Nunca.setSelected(true);

        rbS5Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS5.add(rbS5Poca);

        rbS5Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS5.add(rbS5Moderada);

        rbS5Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS5.add(rbS5Alta);
        rbS5Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS5AltaActionPerformed(evt);
            }
        });

        rbS6Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS6.add(rbS6Nunca);
        rbS6Nunca.setSelected(true);

        rbS6Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS6.add(rbS6Poca);

        rbS6Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS6.add(rbS6Moderada);

        rbS6Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS6.add(rbS6Alta);
        rbS6Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS6AltaActionPerformed(evt);
            }
        });

        rbS7Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS7.add(rbS7Nunca);
        rbS7Nunca.setSelected(true);

        rbS7Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS7.add(rbS7Poca);

        rbS7Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS7.add(rbS7Moderada);

        rbS7Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS7.add(rbS7Alta);
        rbS7Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS7AltaActionPerformed(evt);
            }
        });

        rbS8Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS8.add(rbS8Nunca);
        rbS8Nunca.setSelected(true);

        rbS8Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS8.add(rbS8Poca);

        rbS8Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS8.add(rbS8Moderada);

        rbS8Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS8.add(rbS8Alta);
        rbS8Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS8AltaActionPerformed(evt);
            }
        });

        rbS9Nunca.setBackground(new java.awt.Color(153, 204, 255));
        bgS9.add(rbS9Nunca);
        rbS9Nunca.setSelected(true);

        rbS9Poca.setBackground(new java.awt.Color(153, 204, 255));
        bgS9.add(rbS9Poca);

        rbS9Moderada.setBackground(new java.awt.Color(153, 204, 255));
        bgS9.add(rbS9Moderada);

        rbS9Alta.setBackground(new java.awt.Color(153, 204, 255));
        bgS9.add(rbS9Alta);
        rbS9Alta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbS9AltaActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 51, 51));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pregunta Obligatoria", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 0, 102))); // NOI18N

        rbNo.setBackground(new java.awt.Color(153, 204, 255));
        bgResultado.add(rbNo);
        rbNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbNo.setForeground(new java.awt.Color(0, 0, 153));
        rbNo.setText("NO");

        rbSi.setBackground(new java.awt.Color(153, 204, 255));
        bgResultado.add(rbSi);
        rbSi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbSi.setForeground(new java.awt.Color(0, 0, 153));
        rbSi.setText("SI");

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel84.setText("<html>Usted maneja vehículos motorizados (auto, camioneta, ómnibus, combi, montacarga, grúa, etc.)?<html>");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbSi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbNo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbSi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rbNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel84, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("PUNTAJE");

        txtPuntaje.setText("0");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel45)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(rbS2Nunca)
                                            .addComponent(rbS1Nunca)
                                            .addComponent(rbS3Nunca))
                                        .addGap(35, 35, 35)))
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel16Layout.createSequentialGroup()
                                                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rbS2Poca)
                                                        .addComponent(rbS1Poca))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(rbS1Moderada)
                                                        .addComponent(rbS2Moderada, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(rbS3Moderada, javax.swing.GroupLayout.Alignment.TRAILING))
                                                    .addGap(41, 41, 41)))
                                            .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addComponent(rbS3Poca)
                                                .addGap(115, 115, 115)))
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbS2Alta)
                                            .addComponent(rbS3Alta)
                                            .addComponent(rbS1Alta))))
                                .addGap(97, 97, 97))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(rbS5Nunca)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(rbS5Moderada))
                                            .addComponent(rbS5Poca))
                                        .addGap(41, 41, 41)
                                        .addComponent(rbS5Alta))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(rbS4Nunca)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(rbS4Moderada))
                                            .addComponent(rbS4Poca))
                                        .addGap(41, 41, 41)
                                        .addComponent(rbS4Alta))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(rbS6Nunca)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(rbS6Moderada))
                                            .addComponent(rbS6Poca))
                                        .addGap(41, 41, 41)
                                        .addComponent(rbS6Alta))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addComponent(rbS7Nunca)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(rbS7Moderada))
                                            .addComponent(rbS7Poca))
                                        .addGap(41, 41, 41)
                                        .addComponent(rbS7Alta))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                        .addComponent(rbS8Nunca)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(rbS8Moderada))
                                            .addComponent(rbS8Poca))
                                        .addGap(41, 41, 41)
                                        .addComponent(rbS8Alta))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                        .addComponent(rbS9Nunca)
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel16Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(rbS9Moderada))
                                            .addComponent(rbS9Poca))
                                        .addGap(41, 41, 41)
                                        .addComponent(rbS9Alta)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7))))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel56)
                            .addComponent(jLabel45))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(rbS1Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(rbS2Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(rbS3Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addComponent(rbS1Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(rbS2Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(rbS3Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbS1Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbS1Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbS2Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbS2Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbS3Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbS3Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS4Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS4Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS4Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS4Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbS5Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS5Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS5Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbS5Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS6Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS6Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS6Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS6Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS7Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS7Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS7Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS7Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS8Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS8Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS8Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbS8Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rbS9Alta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbS9Poca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbS9Moderada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbS9Nunca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        Tabla.addTab("Examen ", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "GRABAR/ACTUALIZAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel29.setText("Nombre y Apellidos del Médico – N° de Colegiatura :");

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Imprimir"));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/impresora.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(txtImp, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar.png"))); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/entrar.png"))); // NOI18N
        btnAgregar.setText("Agregar/Actualizar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpiar)))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tabla))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        limpiar(); // TODO add your handling code here:
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       if(oPe.nOrden(txtNorden, "test_fatiga_somnolencia"))  {
           Actualizar();
       }else{
         Agregar();
       }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
         ReImp();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(!txtNorden.getText().isEmpty()){
            FechaNacimiento = new com.toedter.calendar.JDateChooser();
            String Sql="select d.nombres_pa||' '||d.apellidos_pa AS nombre, d.sexo_pa, d.cod_pa, d.fecha_nacimiento_pa , \n" +
"       n.area_o ,n.razon_empresa,t.f_examen, t.rbs1nunca, t.rbs1poca, \n" +
"            t.rbs1moderada, t.rbs1alta, t.rbs2nunca, t.rbs2poca, t.rbs2moderada, t.rbs2alta, \n" +
"            t.rbs3nunca, t.rbs3poca, t.rbs3moderada, t.rbs3alta, t.rbs4nunca, t.rbs4poca, \n" +
"            t.rbs4moderada, t.rbs4alta, t.rbs5nunca, t.rbs5poca, t.rbs5moderada, t.rbs5alta, \n" +
"            t.rbs6nunca, t.rbs6poca, t.rbs6moderada, t.rbs6alta, t.rbs7nunca, t.rbs7poca, \n" +
"            t.rbs7moderada, t.rbs7alta, t.rbs8nunca, t.rbs8poca, t.rbs8moderada, t.rbs8alta, \n" +
"            t.rbs9nunca, t.rbs9poca, t.rbs9moderada, t.rbs9alta, t.rbsi,t.txtpuntaje, t.rbno, t.txtmedico \n" +
"       FROM datos_paciente AS d\n" +
"       INNER JOIN n_orden_ocupacional AS n ON (d.cod_pa=n.cod_pa) \n" +
"       INNER JOIN test_fatiga_somnolencia as t ON (n.n_orden=t.n_orden) " +
            "       WHERE n.n_orden ='"+txtNorden.getText().toString()+"'";
            oConn.FnBoolQueryExecute(Sql);
            try {
                if (oConn.setResult.next()) {
                    txtNombres.setText(oConn.setResult.getString("nombre"));
                    txtdni.setText(oConn.setResult.getString("cod_pa"));
                    FechaNacimiento.setDate(oConn.setResult.getDate("fecha_nacimiento_pa"));
                    txtsexo.setText(oConn.setResult.getString("sexo_pa").equals("M")? "MASCULINO":"FEMENINO") ;
                    txtempresa.setText(oConn.setResult.getString("razon_empresa"));
                    txtareatrabajo.setText(oConn.setResult.getString("area_o"));
                    txtEdad.setText(String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar())) );
                    FechaExamen.setDate(oConn.setResult.getDate("f_examen"));
                    
                    rbS1Nunca.setSelected(oConn.setResult.getBoolean("rbs1nunca"));
                    rbS1Poca.setSelected(oConn.setResult.getBoolean("rbs1poca"));
                    rbS1Moderada.setSelected(oConn.setResult.getBoolean("rbs1moderada"));
                    rbS1Alta.setSelected(oConn.setResult.getBoolean("rbs1alta"));
                    
                    rbS2Nunca.setSelected(oConn.setResult.getBoolean("rbs2nunca"));
                    rbS2Poca.setSelected(oConn.setResult.getBoolean("rbs2poca"));
                    rbS2Moderada.setSelected(oConn.setResult.getBoolean("rbs2moderada"));
                    rbS2Alta.setSelected(oConn.setResult.getBoolean("rbs2alta"));
                    
                    rbS3Nunca.setSelected(oConn.setResult.getBoolean("rbs3nunca"));
                    rbS3Poca.setSelected(oConn.setResult.getBoolean("rbs3poca"));
                    rbS3Moderada.setSelected(oConn.setResult.getBoolean("rbs3moderada"));
                    rbS3Alta.setSelected(oConn.setResult.getBoolean("rbs3alta"));
                    
                    rbS4Nunca.setSelected(oConn.setResult.getBoolean("rbs4nunca"));
                    rbS4Poca.setSelected(oConn.setResult.getBoolean("rbs4poca"));
                    rbS4Moderada.setSelected(oConn.setResult.getBoolean("rbs4moderada"));
                    rbS4Alta.setSelected(oConn.setResult.getBoolean("rbs4alta"));
                    
                    rbS5Nunca.setSelected(oConn.setResult.getBoolean("rbs5nunca"));
                    rbS5Poca.setSelected(oConn.setResult.getBoolean("rbs5poca"));
                    rbS5Moderada.setSelected(oConn.setResult.getBoolean("rbs5moderada"));
                    rbS5Alta.setSelected(oConn.setResult.getBoolean("rbs5alta"));
                    
                    rbS6Nunca.setSelected(oConn.setResult.getBoolean("rbs6nunca"));
                    rbS6Poca.setSelected(oConn.setResult.getBoolean("rbs6poca"));
                    rbS6Moderada.setSelected(oConn.setResult.getBoolean("rbs6moderada"));
                    rbS6Alta.setSelected(oConn.setResult.getBoolean("rbs6alta"));
                    
                    rbS7Nunca.setSelected(oConn.setResult.getBoolean("rbs7nunca"));
                    rbS7Poca.setSelected(oConn.setResult.getBoolean("rbs7poca"));
                    rbS7Moderada.setSelected(oConn.setResult.getBoolean("rbs7moderada"));
                    rbS7Alta.setSelected(oConn.setResult.getBoolean("rbs7alta"));
                    
                    rbS8Nunca.setSelected(oConn.setResult.getBoolean("rbs8nunca"));
                    rbS8Poca.setSelected(oConn.setResult.getBoolean("rbs8poca"));
                    rbS8Moderada.setSelected(oConn.setResult.getBoolean("rbs8moderada"));
                    rbS8Alta.setSelected(oConn.setResult.getBoolean("rbs8alta"));
                    
                    rbS9Nunca.setSelected(oConn.setResult.getBoolean("rbs9nunca"));
                    rbS9Poca.setSelected(oConn.setResult.getBoolean("rbs9poca"));
                    rbS9Moderada.setSelected(oConn.setResult.getBoolean("rbs9moderada"));
                    rbS9Alta.setSelected(oConn.setResult.getBoolean("rbs9alta"));
                    
                    rbSi.setSelected(oConn.setResult.getBoolean("rbsi"));
                    rbNo.setSelected(oConn.setResult.getBoolean("rbno"));
                    txtPuntaje.setText(oConn.setResult.getString("txtpuntaje"));
                    
                    txtMedico.setText(oConn.setResult.getString("txtmedico"));

                }else{
                    oFunc.SubSistemaMensajeError("No se encuentra Registro: \n 1- Intente de nuevo \n 2- Si el error sigue Registre Usuario o \n    Aperture EX-Preocupacional");
                }
                oConn.sqlStmt.close();
            } catch (SQLException ex) {
                oFunc.SubSistemaMensajeInformacion("Error:" + ex.getMessage().toString());
            }

        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNordenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNordenFocusGained
        //limpiar();
    }//GEN-LAST:event_txtNordenFocusGained

    private void txtNordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNordenActionPerformed

        if(!txtNorden.getText().isEmpty()){
            if(!oPe.nOrden(txtNorden, "test_fatiga_somnolencia"))  {
                FechaNacimiento = new com.toedter.calendar.JDateChooser();
                String Sql="select d.nombres_pa||' '||d.apellidos_pa AS nombre, d.sexo_pa, d.cod_pa, d.fecha_nacimiento_pa , "
                + "n.area_o ,n.razon_empresa,n.nom_examen from datos_paciente AS d "
                + "INNER JOIN n_orden_ocupacional AS n ON (d.cod_pa=n.cod_pa) WHERE n.n_orden ='"+txtNorden.getText().toString()+"'";
                oConn.FnBoolQueryExecute(Sql);
                try {
                    if (oConn.setResult.next()) {
                        txtNombres.setText(oConn.setResult.getString("nombre"));
                        txtdni.setText(oConn.setResult.getString("cod_pa"));
                        FechaNacimiento.setDate(oConn.setResult.getDate("fecha_nacimiento_pa"));
                        txtsexo.setText(oConn.setResult.getString("sexo_pa").equals("M")? "MASCULINO":"FEMENINO") ;
                        txtempresa.setText(oConn.setResult.getString("razon_empresa"));
                        txtareatrabajo.setText(oConn.setResult.getString("area_o"));
                        txtNorden.setEditable(false);
                        FechaExamen.requestFocusInWindow();
                        txtEdad.setText(String.valueOf(oFunc.calcularEdad(FechaNacimiento.getCalendar())) );
                        oPe.fecha(FechaExamen);
                        chk();
                    }else{
                        oFunc.SubSistemaMensajeError("No se encuentra Registro: \n 1- Intente de nuevo \n 2- Si el error sigue Registre Usuario o \n    Aperture EX-Preocupacional");
                    }
                    oConn.sqlStmt.close();
                } catch (SQLException ex) {
                    oFunc.SubSistemaMensajeInformacion("Error:" + ex.getMessage().toString());
                }
            }else{
                oFunc.SubSistemaMensajeError("Número de Orden Utilizado");
            }
        }
    }//GEN-LAST:event_txtNordenActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
       cerrarVentana();  // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void rbS3AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS3AltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS3AltaActionPerformed

    private void rbS4AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS4AltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS4AltaActionPerformed

    private void rbS5AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS5AltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS5AltaActionPerformed

    private void rbS6AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS6AltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS6AltaActionPerformed

    private void rbS7AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS7AltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS7AltaActionPerformed

    private void rbS8AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS8AltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS8AltaActionPerformed

    private void rbS9AltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbS9AltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbS9AltaActionPerformed
    
     
    private void Agregar(){
           if(!txtNorden.getText().isEmpty()){
                 if(!oPe.nOrden(txtNorden, "test_fatiga_somnolencia")){
                if(validar()){
            String strSqlStmt;
             String Query ;
            strSqlStmt="INSERT INTO test_fatiga_somnolencia(";
            Query="Values('";
              if (!txtNorden.getText().isEmpty() )
              {strSqlStmt += "n_orden";Query += txtNorden.getText()+ "'";}
              if (txtdni.getText().trim().length()>= 1 )
              {strSqlStmt += ",cod_pa";Query += ",'"+txtdni.getText()+ "'";}
              if (txtEdad.getText().trim().length()>= 1 )
              {strSqlStmt += ",edad";Query += ",'"+txtEdad.getText()+ "'";}
              if (((JTextField)FechaExamen.getDateEditor().getUiComponent()).getText().trim().length()> 1 )
              {strSqlStmt+= ",f_examen";Query+= ",'"+FechaExamen.getDate().toString()+ "'";}
              
              strSqlStmt += ",rbs1nunca";Query += ",'"+rbS1Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs1poca";Query += ",'"+rbS1Poca.isSelected()+ "'";
              strSqlStmt += ",rbs1moderada";Query += ",'"+rbS1Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs1alta";Query += ",'"+rbS1Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs2nunca";Query += ",'"+rbS2Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs2poca";Query += ",'"+rbS2Poca.isSelected()+ "'";
              strSqlStmt += ",rbs2moderada";Query += ",'"+rbS2Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs2alta";Query += ",'"+rbS2Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs3nunca";Query += ",'"+rbS3Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs3poca";Query += ",'"+rbS3Poca.isSelected()+ "'";
              strSqlStmt += ",rbs3moderada";Query += ",'"+rbS3Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs3alta";Query += ",'"+rbS3Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs4nunca";Query += ",'"+rbS4Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs4poca";Query += ",'"+rbS4Poca.isSelected()+ "'";
              strSqlStmt += ",rbs4moderada";Query += ",'"+rbS4Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs4alta";Query += ",'"+rbS4Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs5nunca";Query += ",'"+rbS5Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs5poca";Query += ",'"+rbS5Poca.isSelected()+ "'";
              strSqlStmt += ",rbs5moderada";Query += ",'"+rbS5Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs5alta";Query += ",'"+rbS5Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs6nunca";Query += ",'"+rbS6Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs6poca";Query += ",'"+rbS6Poca.isSelected()+ "'";
              strSqlStmt += ",rbs6moderada";Query += ",'"+rbS6Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs6alta";Query += ",'"+rbS6Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs7nunca";Query += ",'"+rbS7Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs7poca";Query += ",'"+rbS7Poca.isSelected()+ "'";
              strSqlStmt += ",rbs7moderada";Query += ",'"+rbS7Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs7alta";Query += ",'"+rbS7Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs8nunca";Query += ",'"+rbS8Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs8poca";Query += ",'"+rbS8Poca.isSelected()+ "'";
              strSqlStmt += ",rbs8moderada";Query += ",'"+rbS8Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs8alta";Query += ",'"+rbS8Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbs9nunca";Query += ",'"+rbS9Nunca.isSelected()+ "'";
              strSqlStmt += ",rbs9poca";Query += ",'"+rbS9Poca.isSelected()+ "'";
              strSqlStmt += ",rbs9moderada";Query += ",'"+rbS9Moderada.isSelected()+ "'";
              strSqlStmt += ",rbs9alta";Query += ",'"+rbS9Alta.isSelected()+ "'";
              
              strSqlStmt += ",rbsi";Query += ",'"+rbSi.isSelected()+ "'";
              strSqlStmt += ",rbno";Query += ",'"+rbNo.isSelected()+ "'";
              strSqlStmt += ",txtpuntaje";Query += ",'"+txtPuntaje.getText()+ "'";
               strSqlStmt += ",txtmedico";Query += ",'"+txtMedico.getText()+ "'";
               strSqlStmt += ",dni_user";Query += ",'"+clsGlobales.sDniOperador+ "'";                           
              if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt.concat(") ") + Query.concat(")"))){
                    imp();
                    limpiar();   
                    oFunc.SubSistemaMensajeInformacion("Se ha registrado la Entrada con Éxito"); 
                    
                }else{
                    oFunc.SubSistemaMensajeError("No se pudo registrar La Entrada");
                       }
                    try {
                        oConn.sqlStmt.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(EvaluacionMusculoEsqueletica.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
        }else {  oFunc.SubSistemaMensajeError("Llene los Campos correctamente");
        txtNorden.requestFocus();}
    }    
       private boolean validar(){
        boolean bResultado=true;
    if (((JTextField)FechaExamen.getDateEditor().getUiComponent()).getText().trim().length()< 2 ) 
        {oFunc.SubSistemaMensajeError("Ingrese Fecha ");bResultado = false;}
 
   return bResultado;
} 
public void imp(){
    imprimir1(Integer.valueOf(txtNorden.getText()));

}  
private void ReImp(){
if(!txtImp.getText().isEmpty()){
    if(oPe.nOrden(txtImp, "test_fatiga_somnolencia")){
        imprimir1(Integer.valueOf(txtImp.getText()));
    }else {oFunc.SubSistemaMensajeError("Numero de Orden no Existe"); txtImp.setText(null); txtImp.requestFocus();
            }
    }else{
        
    }

}
private void imprimir1(Integer num){
//    boolean im = false;
int seleccion = JOptionPane.showOptionDialog(
    this, // Componente padre
    "¿Desea Imprimir Hoja?", //Mensaje
    "Seleccione una opción", // Título
    JOptionPane.YES_NO_CANCEL_OPTION,
    JOptionPane.QUESTION_MESSAGE,
    null,    // null para icono por defecto.
    new Object[] { "Si", "No"},    // null para YES, NO y CANCEL
    "Si");
    if (seleccion != -1)
    {
        if((seleccion + 1)==1)
        {
           printer1(num);
        }else   {
      // PRESIONO NO
       }
    }
}

private void printer1(Integer cod){
    Map parameters = new HashMap(); 
    parameters.put("Norden",cod);      
        try {
            String master = System.getProperty("user.dir") +
                                "/reportes/TestFatigaSomnolenia.jasper";
            
            System.out.println("master" + master);
            if (master == null) {                
                System.out.println("No encuentro el archivo del ficha antecedente patologico.");
                //System.exit(2);
            } 
            JasperReport masterReport = null;
            try 
            {
                masterReport = (JasperReport) JRLoader.loadObject(master);
            } 
            catch (JRException e) 
            {
                System.out.println("Error cargando el reporte maestro: " + e.getMessage());
                System.exit(3);
            } 
            if(!txtImp.getText().isEmpty()){
                JasperPrint myPrint = JasperFillManager.fillReport(masterReport,parameters,clsConnection.oConnection);
                           
                JasperViewer.viewReport(myPrint,false);
            }else{
                JasperPrint jasperPrint= JasperFillManager.fillReport(masterReport,parameters,clsConnection.oConnection);
                JasperPrintManager.printReport(jasperPrint,true);
            }
            } catch (JRException ex) {
                    Logger.getLogger(EvaluacionMusculoEsqueletica.class.getName()).log(Level.SEVERE, null, ex);
            }
 }

    private void limpiar(){
        txtNorden.setText(null);
        txtNombres.setText(null);
        txtdni.setText(null);
        txtEdad.setText(null);
        txtsexo.setText(null);
        txtempresa.setText(null);
        txtareatrabajo.setText(null);
        FechaExamen.setDate(null);
        txtPuntaje.setText("0");
        rbS1Nunca.setSelected(true);
        rbS2Nunca.setSelected(true);
        rbS3Nunca.setSelected(true);
        rbS4Nunca.setSelected(true);
        rbS5Nunca.setSelected(true);
        rbS6Nunca.setSelected(true);
        rbS7Nunca.setSelected(true);
        rbS8Nunca.setSelected(true);
        rbS9Nunca.setSelected(true);
//        bgS1.clearSelection();
//        bgS2.clearSelection();
//        bgS3.clearSelection();
//        bgS4.clearSelection();
//       
//        bgS5.clearSelection();
//        bgS6.clearSelection();
//        bgS7.clearSelection();
//        bgS8.clearSelection();
//        bgS9.clearSelection();
        bgResultado.clearSelection();
        
        
       
       txtMedico.setText(null);
        //Regresamos el Foco a N orden
        
        txtNorden.setEditable(true);
        txtNorden.requestFocus();
        
        
    }
      
   public void chk(){
       
       
      
   }
   
   public void cerrarVentana(){
        // JOptionPane.showMessageDialog(null, "probando para cerrar el stament");
        System.out.println("cerro esta ventana");
        
        try {
            oConn.sqlStmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(TestFatigaSomnolencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    
      //  System.exit(0);

    }

   public void Actualizar(){
       String sCodigo=txtNorden.getText();
       if(!txtNorden.getText().isEmpty()){
                if(validar()){
            String strSqlStmt;
             String Query ;
            strSqlStmt="UPDATE test_fatiga_somnolencia ";
            Query="SET ";
              if (txtdni.getText().trim().length()>= 1 )
              {Query += "cod_pa='"+txtdni.getText().toString()+ "'";}
              if (txtEdad.getText().trim().length()>= 1 )
              {Query += ",edad='"+txtEdad.getText().toString()+ "'";}
              if (((JTextField)FechaExamen.getDateEditor().getUiComponent()).getText().trim().length()> 1 )
              {Query+= ",f_examen='"+FechaExamen.getDate().toString()+ "'";}
              
               Query += ",rbs1nunca='"+rbS1Nunca.isSelected()+ "'";
               Query += ",rbs1poca='"+rbS1Poca.isSelected()+ "'";
               Query += ",rbs1moderada='"+rbS1Moderada.isSelected()+ "'";
               Query += ",rbs1alta='"+rbS1Alta.isSelected()+ "'";
               
               Query += ",rbs2nunca='"+rbS2Nunca.isSelected()+ "'";
               Query += ",rbs2poca='"+rbS2Poca.isSelected()+ "'";
               Query += ",rbs2moderada='"+rbS2Moderada.isSelected()+ "'";
               Query += ",rbs2alta='"+rbS2Alta.isSelected()+ "'";
               
               Query += ",rbs3nunca='"+rbS3Nunca.isSelected()+ "'";
               Query += ",rbs3poca='"+rbS3Poca.isSelected()+ "'";
               Query += ",rbs3moderada='"+rbS3Moderada.isSelected()+ "'";
               Query += ",rbs3alta='"+rbS3Alta.isSelected()+ "'";
               
               Query += ",rbs4nunca='"+rbS4Nunca.isSelected()+ "'";
               Query += ",rbs4poca='"+rbS4Poca.isSelected()+ "'";
               Query += ",rbs4moderada='"+rbS4Moderada.isSelected()+ "'";
               Query += ",rbs4alta='"+rbS4Alta.isSelected()+ "'";
               
               Query += ",rbs5nunca='"+rbS5Nunca.isSelected()+ "'";
               Query += ",rbs5poca='"+rbS5Poca.isSelected()+ "'";
               Query += ",rbs5moderada='"+rbS5Moderada.isSelected()+ "'";
               Query += ",rbs5alta='"+rbS5Alta.isSelected()+ "'";
               
               Query += ",rbs6nunca='"+rbS6Nunca.isSelected()+ "'";
               Query += ",rbs6poca='"+rbS6Poca.isSelected()+ "'";
               Query += ",rbs6moderada='"+rbS6Moderada.isSelected()+ "'";
               Query += ",rbs6alta='"+rbS6Alta.isSelected()+ "'";
               
               Query += ",rbs7nunca='"+rbS7Nunca.isSelected()+ "'";
               Query += ",rbs7poca='"+rbS7Poca.isSelected()+ "'";
               Query += ",rbs7moderada='"+rbS7Moderada.isSelected()+ "'";
               Query += ",rbs7alta='"+rbS7Alta.isSelected()+ "'";
               
               Query += ",rbs8nunca='"+rbS8Nunca.isSelected()+ "'";
               Query += ",rbs8poca='"+rbS8Poca.isSelected()+ "'";
               Query += ",rbs8moderada='"+rbS8Moderada.isSelected()+ "'";
               Query += ",rbs8alta='"+rbS8Alta.isSelected()+ "'";
               
               Query += ",rbs9nunca='"+rbS9Nunca.isSelected()+ "'";
               Query += ",rbs9poca='"+rbS9Poca.isSelected()+ "'";
               Query += ",rbs9moderada='"+rbS9Moderada.isSelected()+ "'";
               Query += ",rbs9alta='"+rbS9Alta.isSelected()+ "'";
               Query += ",rbsi='"+rbSi.isSelected()+ "'";
               Query += ",rbno='"+rbNo.isSelected()+ "'";
               Query += ",txtpuntaje='"+txtPuntaje.getText()+ "'";
               Query += ",txtmedico='"+txtMedico.getText()+ "'";
               Query += ",dni_user='"+ clsGlobales.sDniOperador + "'";
//             oFunc.SubSistemaMensajeError(strSqlStmt+Query);
                Query +=" WHERE n_orden='" + sCodigo + "'";
              if (oConn.FnBoolQueryExecuteUpdate(strSqlStmt + Query)){
                  oFunc.SubSistemaMensajeInformacion("Se ha actualizado con Éxito");
                  imp();
                  limpiar();               
        }else{
             oFunc.SubSistemaMensajeError("No se pudo registrar La Entrada");
        }
        try {
            oConn.sqlStmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(EvaluacionMusculoEsqueletica.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }else {  oFunc.SubSistemaMensajeError("Llene los Campos correctamente");
        txtNorden.requestFocus();}
   }     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaExamen;
    private javax.swing.JTabbedPane Tabla;
    private javax.swing.ButtonGroup bgResultado;
    private javax.swing.ButtonGroup bgS1;
    private javax.swing.ButtonGroup bgS2;
    private javax.swing.ButtonGroup bgS3;
    private javax.swing.ButtonGroup bgS4;
    private javax.swing.ButtonGroup bgS5;
    private javax.swing.ButtonGroup bgS6;
    private javax.swing.ButtonGroup bgS7;
    private javax.swing.ButtonGroup bgS8;
    private javax.swing.ButtonGroup bgS9;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbS1Alta;
    private javax.swing.JRadioButton rbS1Moderada;
    private javax.swing.JRadioButton rbS1Nunca;
    private javax.swing.JRadioButton rbS1Poca;
    private javax.swing.JRadioButton rbS2Alta;
    private javax.swing.JRadioButton rbS2Moderada;
    private javax.swing.JRadioButton rbS2Nunca;
    private javax.swing.JRadioButton rbS2Poca;
    private javax.swing.JRadioButton rbS3Alta;
    private javax.swing.JRadioButton rbS3Moderada;
    private javax.swing.JRadioButton rbS3Nunca;
    private javax.swing.JRadioButton rbS3Poca;
    private javax.swing.JRadioButton rbS4Alta;
    private javax.swing.JRadioButton rbS4Moderada;
    private javax.swing.JRadioButton rbS4Nunca;
    private javax.swing.JRadioButton rbS4Poca;
    private javax.swing.JRadioButton rbS5Alta;
    private javax.swing.JRadioButton rbS5Moderada;
    private javax.swing.JRadioButton rbS5Nunca;
    private javax.swing.JRadioButton rbS5Poca;
    private javax.swing.JRadioButton rbS6Alta;
    private javax.swing.JRadioButton rbS6Moderada;
    private javax.swing.JRadioButton rbS6Nunca;
    private javax.swing.JRadioButton rbS6Poca;
    private javax.swing.JRadioButton rbS7Alta;
    private javax.swing.JRadioButton rbS7Moderada;
    private javax.swing.JRadioButton rbS7Nunca;
    private javax.swing.JRadioButton rbS7Poca;
    private javax.swing.JRadioButton rbS8Alta;
    private javax.swing.JRadioButton rbS8Moderada;
    private javax.swing.JRadioButton rbS8Nunca;
    private javax.swing.JRadioButton rbS8Poca;
    private javax.swing.JRadioButton rbS9Alta;
    private javax.swing.JRadioButton rbS9Moderada;
    private javax.swing.JRadioButton rbS9Nunca;
    private javax.swing.JRadioButton rbS9Poca;
    private javax.swing.JRadioButton rbSi;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtImp;
    private javax.swing.JTextField txtMedico;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNorden;
    private javax.swing.JTextField txtPuntaje;
    private javax.swing.JTextField txtareatrabajo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtempresa;
    private javax.swing.JTextField txtsexo;
    // End of variables declaration//GEN-END:variables
}
