/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Caja;

import Clases.clsConnection;
import Clases.clsFunciones;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josue
 */
public class hoteles extends javax.swing.JFrame {

      clsFunciones  oFunc = new clsFunciones();
      clsConnection oConn = new clsConnection();
      int estadoSede,operacion;
      String id="12";
         DefaultTableModel model;
    /**
     * Creates new form sede
     */
    public hoteles() {
        initComponents();
//sbCargarDatosEmpresa("");  
//this.setAlwaysOnTop( true );
mostrar();

popuptable();
    }
    
            public void popuptable(){
    JPopupMenu popupMenu=new JPopupMenu();
    JMenuItem menuItem1=new JMenuItem("Eliminar Registro");
    menuItem1.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae) {
            operacion=3;
     int a =tabla.getSelectedRow();
       System.out.println("la fila es:"+a);
     
     id= (String) tabla.getValueAt(a,0);
     System.out.println("la id es :"+id);
     
           funcionosede();
               JOptionPane.showMessageDialog(null, "Registro Eliminado");
                    mostrar();
        }
    
    });    
    popupMenu.add(menuItem1);
    tabla.setComponentPopupMenu(popupMenu);
  
    }  
    
    
  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFielddireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreacomentario = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jCheckBoxHabilitado = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 3, 18)); // NOI18N
        jLabel1.setText("Hoteles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 66, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo hotel", "Nombre del hotel", "Direccion", "Comentario", "Estado"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tablaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 323, 693, 173));

        jLabel2.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 80, 66, -1));

        jTextFielddireccion.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        getContentPane().add(jTextFielddireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 124, 233, 32));

        jLabel3.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel3.setText("Direccion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 124, 78, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jTextFieldNombre.setToolTipText("");
        jTextFieldNombre.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 74, 233, 32));

        jLabel4.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel4.setText("Comentario:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 200, 87, -1));

        jTextAreacomentario.setColumns(20);
        jTextAreacomentario.setRows(5);
        jScrollPane2.setViewportView(jTextAreacomentario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 186, 233, 62));

        jLabel5.setFont(new java.awt.Font("Ebrima", 3, 14)); // NOI18N
        jLabel5.setText("Estado:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 275, 87, -1));

        jCheckBoxHabilitado.setText("Habilitado");
        jCheckBoxHabilitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHabilitadoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxHabilitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 273, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 91, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxHabilitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHabilitadoActionPerformed
      if (jCheckBoxHabilitado.isSelected()) {
      estadoSede=1;
      }
      else
          estadoSede=0;
    
    }//GEN-LAST:event_jCheckBoxHabilitadoActionPerformed

    public void mostrar(){
           
          try {
              String [] titulos={"Codigo","Nombre de la sede","Dirección","Comentarios","Estado"};
              String [] registros = new String[5];
              String sql="select idHotel, nombreHotel, direccion,comentarios, "
                      + "(CASE WHEN estado='1' THEN 'HABILITADO' ELSE 'DESHABILITADO' END) AS estadito from InfoHoteles order by idHotel;";
              model = new DefaultTableModel(null,titulos);
              System.out.println("paso el model");
              
              if (oConn.FnBoolQueryExecute(sql))
              {
                  try  {
                      
                      while (oConn.setResult.next())
                      {
                          registros[0]= oConn.setResult.getString("idHotel");
                          registros[1]= oConn.setResult.getString("nombreHotel");
                          registros[2]= oConn.setResult.getString("direccion");
                          registros[3]= oConn.setResult.getString("comentarios");
                          registros[4]= oConn.setResult.getString("estadito");
                          model.addRow(registros);
                      }
                      System.out.println("registro 0"+registros[0]);
                      
                      
                      tabla.setModel(model);
                      
                      oConn.setResult.close();
                      //   System.out.println("la cantida de filas en hotel es"+tabla.getRowCount());
                      
                  }
                  catch (SQLException ex)
                  {
                      JOptionPane.showMessageDialog(null, ex);
                      oFunc.SubSistemaMensajeError(ex.toString());
                      Logger.getLogger(hoteles.class.getName()).log(Level.SEVERE, null, ex);
                  }
              }
              oConn.sqlStmt.close();
              oConn.setResult.close();
          } catch (SQLException ex) {
              Logger.getLogger(hoteles.class.getName()).log(Level.SEVERE, null, ex);
          }

}
     public boolean OrdenExisteIn()
    {
        boolean bResultado=false;
        if(!jTextFieldNombre.getText().isEmpty()){
        String sQuery;
        sQuery  = "Select * from InfoHoteles Where nombreHotel ='"+jTextFieldNombre.getText().toString()+"'";
        oConn.FnBoolQueryExecute(sQuery);
        try {
            if (oConn.setResult.next())
            {
                bResultado = true;
//             oFunc.SubSistemaMensajeError("Número de Orden Utilizado");
//             txtNorden.setText(null);
            }
            oConn.sqlStmt.close();
            oConn.setResult.close();

        } catch (SQLException ex) {
        }
        }       
        return bResultado;
     }   
    
    
    public void funcionosede(){
            
 
          try {
              String [] registros = new String[5];
              String sql="";
              sql="select spFuncionHotelOperaciones("+id+",'"+jTextFieldNombre.getText()+"','"+jTextFielddireccion.getText()+"','"
                      +jTextAreacomentario.getText()+"','"+estadoSede+"',"+operacion+");";
              
              oConn.FnBoolQueryExecute(sql);
              
              System.out.println(sql);
              oConn.sqlStmt.close();
              oConn.setResult.close();
          } catch (SQLException ex) {
              Logger.getLogger(hoteles.class.getName()).log(Level.SEVERE, null, ex);
          }

    
    }
    
    
    private void tablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMousePressed
     if (evt.getClickCount() == 2) {
     int a =tabla.getSelectedRow();
     id= (String) tabla.getValueAt(a,0);
     jTextFieldNombre.setText((String)  tabla.getValueAt(a,1));
     jTextFielddireccion.setText((String)  tabla.getValueAt(a,2));
     jTextAreacomentario.setText((String)  tabla.getValueAt(a,3));
     String esta=(String) tabla.getValueAt(a,4);
     if(esta.equals("1"))
         jCheckBoxHabilitado.setSelected(true);
     else
          jCheckBoxHabilitado.setSelected(false);
     }
    }//GEN-LAST:event_tablaMousePressed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
      
    }//GEN-LAST:event_tablaMouseClicked

    private void tablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(!jTextFieldNombre.getText().isEmpty())
     {
     if(!OrdenExisteIn()){   
        operacion=1;
        funcionosede();
        
     }
     else 
          JOptionPane.showMessageDialog(null, "YA EXISTE UN REGISTRO CON EL MISMO NOMBRE");
     }
     else 
     JOptionPane.showMessageDialog(null, "LLENE LOS DATOS PARA PODER REGISTRAR");
     mostrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
mostrar();        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 if(!jTextFieldNombre.getText().isEmpty())
     {
        if(!jTextFieldNombre.getText().isEmpty()){
            operacion=2;
            int a =tabla.getSelectedRow();
        id= (String) tabla.getValueAt(a,0);
            funcionosede();
             JOptionPane.showMessageDialog(null, "SE ACTUALIZO CORRECTAMENTE");
        }
     }
    else 
     JOptionPane.showMessageDialog(null, "LLENE LOS DATOS PARA PODER ACTUALIZAR LOS REGISTROS");
  mostrar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        operacion=0;
        estadoSede=0;
        jTextFieldNombre.setText("");
        jTextFielddireccion.setText("");
        jTextAreacomentario.setText("");
        jCheckBoxHabilitado.setSelected(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed
public void cerrarVentana(){
        // JOptionPane.showMessageDialog(null, "probando para cerrar el stament");
        System.out.println("cerro esta ventana");
          try {
              oConn.sqlStmt.close();
          } catch (SQLException ex) {
              Logger.getLogger(hoteles.class.getName()).log(Level.SEVERE, null, ex);
          }
  
    this.dispose();
      //  System.exit(0);

    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarVentana();// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoteles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBoxHabilitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreacomentario;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFielddireccion;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
